-- MID SYSTEM DESIGN 질문 Pool 시딩 (30문항: 캐싱6, 메시지큐6, 마이크로서비스6, 로드밸런싱6, API설계6)
-- referenceType: MODEL_ANSWER (상세 기술 모범답변)
-- V20 이후 스키마 기준 (question_order, evaluation_criteria, follow_up_strategy, quality_score 컬럼 없음)

-- ============================================================
-- 캐싱 (6문항)
-- ============================================================

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'Write-Through와 Write-Behind(Write-Back) 캐시 전략의 차이점과 각각의 장단점은?', '캐싱',
 '**Write-Through:**\n데이터 쓰기 시 캐시와 DB를 동시에(동기적으로) 업데이트하는 전략.\n\n```\n쓰기 요청 → [캐시 업데이트] + [DB 업데이트] → 완료 응답\n// 두 저장소 동시 업데이트, 성공 시에만 응답\n```\n\n**장점:**\n- 캐시-DB 일관성 항상 보장\n- 캐시 장애 후 재기동 시 데이터 손실 없음\n\n**단점:**\n- 쓰기 레이턴시 증가 (캐시 + DB 모두 완료 후 응답)\n- 거의 읽히지 않는 데이터도 캐시에 저장됨 (메모리 낭비)\n\n---\n\n**Write-Behind (Write-Back):**\n데이터 쓰기 시 캐시만 즉시 업데이트하고 DB는 비동기로 나중에 반영.\n\n```\n쓰기 요청 → [캐시 업데이트] → 즉시 응답\n                  ↓ (비동기, 배치)\n             [DB 업데이트]\n```\n\n**장점:**\n- 쓰기 레이턴시 매우 낮음\n- DB 부하 감소 (배치 업데이트로 여러 쓰기를 묶음)\n- 쓰기가 많은 워크로드에 효과적\n\n**단점:**\n- 캐시 장애 시 아직 DB에 반영되지 않은 데이터 손실 가능\n- 구현 복잡도 높음\n- 일관성 보장이 어려움\n\n**선택 기준:**\n| 상황 | 전략 |\n|------|------|\n| 데이터 손실 허용 불가 (금융, 주문) | Write-Through |\n| 쓰기 성능이 핵심 (로그, 이벤트 카운터) | Write-Behind |\n| 읽기 중심 서비스 | Cache-Aside |',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'Cache Stampede(캐시 스탬피드) 문제란 무엇이고 어떻게 방지하나요?', '캐싱',
 '**Cache Stampede (Thundering Herd):**\n인기 있는 캐시 항목이 만료되는 순간, 다수의 요청이 동시에 캐시 미스 → DB로 쏟아지는 현상.\n\n```\n인기 데이터 TTL 만료\n→ 동시 요청 1000개 → 캐시 미스\n→ 1000개 DB 쿼리 동시 발생\n→ DB 과부하 → 장애 가능성\n```\n\n**해결 방법:**\n\n**1. Mutex Lock (분산 락):**\n```\n캐시 미스 → 락 획득 시도\n→ 락 획득 성공: DB 조회 → 캐시 저장 → 락 해제\n→ 락 획득 실패: 락 해제 대기 → 캐시 재조회\n// Redis SETNX로 구현\n```\n단점: 락 대기로 레이턴시 증가\n\n**2. Probabilistic Early Recomputation (확률적 조기 갱신):**\n```java\n// TTL이 얼마 남지 않았을 때 일부 요청에서 확률적으로 조기 갱신\ndouble remainingTtl = cache.getTtl(key);\ndouble beta = 1.0;\nif (currentTime - beta * Math.log(Math.random()) >= expiryTime) {\n    // 캐시 만료 전 미리 갱신\n    recomputeAndCache(key);\n}\n```\n\n**3. TTL 지터(Jitter) 추가:**\n```java\n// 모든 캐시가 같은 시점에 만료되지 않도록 랜덤 오프셋 추가\nint ttlWithJitter = baseTtl + random.nextInt(300); // ±5분\nredis.set(key, value, ttlWithJitter);\n```\n\n**4. 백그라운드 갱신 (Stale-While-Revalidate):**\n```\n캐시 만료 임박 → 기존 데이터 계속 반환\n백그라운드에서 비동기 갱신 → 갱신 완료 시 캐시 교체\n```\n\n**실무 권장:** 중요 캐시는 Jitter + 백그라운드 갱신 조합',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', '분산 환경에서 캐시 일관성(Cache Consistency)을 유지하는 방법은?', '캐싱',
 '**문제 상황:**\n여러 서버 인스턴스가 각자 로컬 캐시를 가지면, DB 업데이트 후 일부 서버만 갱신되어 불일치 발생.\n\n```\n[서버1 캐시: 가격=1000] [서버2 캐시: 가격=1200]\n↓ 업데이트 요청이 서버1에 도달\n[DB: 가격=1200]\n[서버1 캐시: 1200] [서버2 캐시: 1000 ← 오래된 데이터]\n```\n\n**해결 방법:**\n\n**1. 중앙화된 캐시 (Redis) 사용:**\n```\n[서버1] [서버2] [서버3]\n    ↓       ↓       ↓\n    [Redis 캐시 — 단일 진실 공급원]\n```\n모든 서버가 동일한 캐시 데이터 참조 → 일관성 보장\n\n**2. Cache Invalidation on Write:**\n```java\n// 데이터 변경 시 관련 캐시 즉시 삭제\n@Transactional\npublic void updateProduct(Long id, ProductRequest req) {\n    productRepository.update(id, req);\n    cacheManager.evict("products", id); // 캐시 삭제\n}\n```\n\n**3. Event-Driven Cache Invalidation:**\n```\nDB 업데이트 → [이벤트 발행] → Kafka/Redis Pub/Sub\n               → 모든 서버 수신 → 로컬 캐시 무효화\n```\n\n**4. Cache-Aside + 짧은 TTL:**\n- 완벽한 일관성보다 일시적 불일치 허용\n- 짧은 TTL(수 초~분)로 자연스럽게 갱신\n\n**일관성 수준 선택:**\n| 수준 | 방법 | 사용 케이스 |\n|------|------|------------|\n| Strong | 중앙 캐시 + 즉시 무효화 | 재고, 잔액 |\n| Eventual | 이벤트 기반 무효화 | 프로필, 게시글 |\n| Weak | 짧은 TTL | 추천, 통계 |',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'Redis의 데이터 영속성 옵션(RDB vs AOF)을 비교해주세요.', '캐싱',
 'Redis는 메모리 기반 저장소이지만, 재시작 후 데이터 복구를 위한 두 가지 영속성 방식을 제공합니다.\n\n**RDB (Redis Database Snapshot):**\n지정된 시간 간격으로 전체 데이터를 스냅샷으로 디스크에 저장.\n\n```\n# redis.conf\nsave 900 1      # 900초마다, 1개 이상 변경 시 저장\nsave 300 10     # 300초마다, 10개 이상 변경 시 저장\nsave 60 10000   # 60초마다, 10000개 이상 변경 시 저장\n```\n\n**RDB 장점:**\n- 컴팩트한 단일 파일 → 백업/복원 용이\n- Fork 기반 백그라운드 저장 → 성능 영향 낮음\n- 대용량 데이터 복구 속도 빠름\n\n**RDB 단점:**\n- 스냅샷 간격 동안 데이터 손실 가능 (예: 5분치 데이터)\n- Fork 시 메모리 사용량 일시 증가\n\n---\n\n**AOF (Append Only File):**\n모든 쓰기 명령을 로그 파일에 순서대로 기록.\n\n```\n# redis.conf\nappendonly yes\nappendfsync everysec   # 1초마다 fsync (기본 권장)\n# appendfsync always   # 매 명령마다 fsync (느림, 안전)\n# appendfsync no       # OS에 위임 (빠름, 위험)\n```\n\n**AOF 장점:**\n- 최대 1초치 데이터만 손실 가능\n- 파일이 인간이 읽을 수 있는 형태\n- AOF 재작성으로 파일 크기 관리\n\n**AOF 단점:**\n- RDB보다 파일 크기 큼\n- 복구 속도 느림 (명령 재실행)\n\n**권장 구성 (실무):**\n```\nRDB + AOF 동시 사용\n→ RDB: 주기적 백업\n→ AOF: 장애 시 최소 손실 복구\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'Redis Cluster와 Redis Sentinel의 차이점은 무엇인가요?', '캐싱',
 '두 방식 모두 Redis 고가용성(HA)을 위한 구성이지만 목적과 방식이 다릅니다.\n\n**Redis Sentinel:**\n마스터-레플리카 구조에서 마스터 장애 시 자동 페일오버(Failover)를 담당하는 모니터링 프로세스.\n\n```\n[Sentinel1] [Sentinel2] [Sentinel3]  ← 과반수 합의로 페일오버 결정\n      ↓\n[Master] → [Replica1] [Replica2]\n\n마스터 장애 시:\n→ Sentinel들이 감지 → 과반수 합의 → Replica1을 Master로 승격\n→ 클라이언트에 새 Master 주소 알림\n```\n\n**Sentinel 특징:**\n- 단일 마스터 → 수직 확장만 가능\n- 쓰기는 마스터 한 곳에만\n- Sentinel 3개 이상 권장 (과반수 합의)\n- 용량 한계: 단일 마스터의 메모리 한계\n\n---\n\n**Redis Cluster:**\n데이터를 여러 샤드(마스터)에 분산 저장하는 수평 확장 구조.\n\n```\n[Master1 + Replica1]  ← 키 슬롯 0~5460\n[Master2 + Replica2]  ← 키 슬롯 5461~10922\n[Master3 + Replica3]  ← 키 슬롯 10923~16383\n// 16384개의 해시 슬롯을 분산\n```\n\n**Cluster 특징:**\n- 수평 확장 가능 (노드 추가로 용량 증가)\n- 자동 샤딩 (CRC16 해시 기반)\n- 마스터 장애 시 자체 페일오버\n- 최소 3개의 마스터 + 3개의 레플리카 필요\n\n**선택 기준:**\n| 기준 | Sentinel | Cluster |\n|------|----------|---------|\n| 데이터 크기 | 단일 인스턴스 내 | 멀티 노드 분산 |\n| 확장 방식 | 수직 확장 | 수평 확장 |\n| 복잡도 | 낮음 | 높음 |\n| 적합한 경우 | 중소 규모 | 대용량 데이터 |',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', '캐시 웜업(Cache Warming)이란 무엇이고 언제 필요한가요?', '캐싱',
 '**Cache Warming (캐시 예열):**\n애플리케이션 시작 또는 배포 직후 빈 캐시(Cold Cache) 상태에서 주요 데이터를 미리 캐시에 적재하는 작업.\n\n**문제 상황 (Cold Cache):**\n```\n배포 직후:\n→ 캐시 비어있음\n→ 모든 요청이 DB로 → DB 과부하\n→ 응답 속도 저하, 장애 가능성\n```\n\n**캐시 웜업이 필요한 경우:**\n1. 서비스 재시작/배포 직후\n2. 캐시 서버 교체 후\n3. 예상되는 트래픽 급증 전 (이벤트, 출시)\n\n**웜업 전략:**\n\n**1. 시작 시 자동 웜업:**\n```java\n@Component\n@RequiredArgsConstructor\npublic class CacheWarmUp implements ApplicationRunner {\n    private final ProductService productService;\n    private final CacheManager cacheManager;\n\n    @Override\n    public void run(ApplicationArguments args) {\n        // 인기 상품 Top 100을 캐시에 미리 로드\n        List<Product> topProducts = productService.findTop100();\n        topProducts.forEach(p ->\n            cacheManager.getCache("products").put(p.getId(), p)\n        );\n    }\n}\n```\n\n**2. 배포 전 트래픽 전환:**\n```\n신규 인스턴스 시작 → 웜업 API 호출\n→ 캐시 충분히 채워진 후 로드밸런서에 등록\n→ 트래픽 수신 시작\n```\n\n**3. 쉐도우 트래픽(Shadow Traffic):**\n실제 트래픽 일부를 신규 인스턴스에 미러링하여 웜업\n\n**주의사항:**\n- 웜업 데이터가 너무 많으면 시작 시간 증가\n- TTL 없는 데이터를 웜업하면 메모리 낭비\n- 웜업 완료 전 헬스 체크 Fail 처리 권장',
 'MODEL_ANSWER', TRUE, NOW());

-- ============================================================
-- 메시지큐 (6문항)
-- ============================================================

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'Kafka의 파티션(Partition)과 컨슈머 그룹(Consumer Group)의 동작 원리를 설명해주세요.', '메시지큐',
 '**Kafka 토픽 구조:**\n```\nTopic: orders\n├── Partition 0: [msg1] [msg4] [msg7]\n├── Partition 1: [msg2] [msg5] [msg8]\n└── Partition 2: [msg3] [msg6] [msg9]\n```\n\n**파티션 특성:**\n- 각 파티션 내에서만 메시지 순서 보장\n- 파티션 간 순서 보장 없음\n- 파티션이 병렬 처리의 단위\n- 파티션 수 = 최대 병렬 Consumer 수\n\n**파티션 키(Partition Key):**\n```java\n// 동일 키는 같은 파티션으로 → 순서 보장\nproducer.send(new ProducerRecord<>(\n    "orders",\n    userId.toString(), // key → 파티션 결정\n    orderJson\n));\n// userId가 같은 주문은 항상 같은 파티션 → 순서 처리 가능\n```\n\n**Consumer Group:**\n```\nConsumer Group A (주문 처리 서비스)\n├── Consumer1 → Partition0\n├── Consumer2 → Partition1\n└── Consumer3 → Partition2\n\nConsumer Group B (알림 서비스)\n├── Consumer1 → Partition0\n├── Consumer2 → Partition1\n└── Consumer3 → Partition2\n// 동일 토픽을 독립적으로 소비\n```\n\n**핵심 규칙:**\n- 하나의 파티션은 Consumer Group 내 Consumer 1개에만 할당\n- Consumer > Partition이면 초과 Consumer는 유휴\n- Consumer 추가/제거 시 리밸런싱 발생\n\n**오프셋 관리:**\n```\nConsumer는 처리 완료 후 오프셋 커밋\n→ 장애 후 재시작 시 커밋된 오프셋부터 재처리\n→ enable.auto.commit=false로 수동 커밋 권장\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'Kafka에서 메시지 순서 보장과 중복 처리를 어떻게 다루나요?', '메시지큐',
 '**메시지 순서 보장:**\n\nKafka는 파티션 내에서만 순서를 보장합니다.\n\n```\n// 파티션 내 순서 보장\nPartition 0: [주문생성] → [결제완료] → [배송시작]  ← 순서 보장\nPartition 1: [주문생성] → [결제완료]               ← 독립적 순서\n\n// 파티션 간 순서 불보장\nPartition 0의 msg와 Partition 1의 msg 간 순서는 보장 안 됨\n```\n\n**특정 엔티티 순서 보장 방법:**\n```java\n// 동일 userId는 항상 같은 파티션으로\nproducer.send(new ProducerRecord<>(\n    "user-events",\n    userId.toString(), // 파티션 키\n    eventJson\n));\n```\n\n**중복 처리 (Duplicate Processing):**\n\nat-least-once 환경에서는 중복 메시지가 발생할 수 있습니다.\n\n**원인:**\n- Consumer가 처리 후 오프셋 커밋 전에 장애 → 재시작 시 동일 메시지 재처리\n\n**해결책 1: 멱등성 Consumer 설계**\n```java\n// DB에 처리된 메시지 ID 저장\npublic void processOrder(OrderEvent event) {\n    if (processedEventRepository.exists(event.getEventId())) {\n        return; // 이미 처리된 메시지 스킵\n    }\n    // 실제 처리\n    processedEventRepository.save(event.getEventId());\n}\n```\n\n**해결책 2: Kafka exactly-once (EOS)**\n```properties\nenable.idempotence=true           # Producer 중복 전송 방지\ntransactional.id=my-transactional-id  # 트랜잭션 Producer\nisolation.level=read_committed    # Consumer — 커밋된 것만 읽기\n```\n복잡도 증가 + 성능 감소 → 꼭 필요한 경우만 사용',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'Outbox 패턴이란 무엇이고 왜 필요한가요?', '메시지큐',
 '**문제 상황:**\n비즈니스 로직(DB 저장)과 이벤트 발행을 원자적으로 처리하기 어렵습니다.\n\n```java\n// 위험한 코드\n@Transactional\npublic void createOrder(OrderRequest req) {\n    Order order = orderRepository.save(req.toEntity());\n    kafka.send("order-created", order); // 여기서 실패하면?\n    // DB는 커밋됐지만 이벤트는 발행 안 됨 → 불일치\n}\n```\n\n**Outbox 패턴:**\n이벤트를 Kafka에 직접 보내지 않고, DB의 Outbox 테이블에 먼저 저장 → 별도 프로세스가 Outbox를 읽어 Kafka로 발행.\n\n**구조:**\n```\n[비즈니스 트랜잭션]\n├── orders 테이블에 주문 저장\n└── outbox 테이블에 이벤트 저장  ← 같은 트랜잭션!\n↓\n[Outbox Poller/CDC]\n└── outbox 읽기 → Kafka 발행 → 발행 완료 표시\n```\n\n**Outbox 테이블:**\n```sql\nCREATE TABLE outbox (\n    id BIGINT PRIMARY KEY AUTO_INCREMENT,\n    aggregate_type VARCHAR(50),  -- ''ORDER''\n    aggregate_id BIGINT,\n    event_type VARCHAR(100),     -- ''OrderCreated''\n    payload JSON,\n    created_at DATETIME,\n    processed_at DATETIME        -- NULL이면 미처리\n);\n```\n\n**장점:**\n- 비즈니스 로직과 이벤트 발행의 원자성 보장\n- Kafka 장애 시에도 이벤트 유실 없음\n- 재시도 로직 단순화\n\n**단점:**\n- Outbox 테이블 폴링 또는 CDC(Debezium) 구성 필요\n- 구현 복잡도 증가\n\n**CDC 활용 (Debezium):**\nDB binlog를 읽어 자동으로 Kafka에 발행 → 폴링 불필요',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'Event Sourcing이란 무엇이고 어떤 장단점이 있나요?', '메시지큐',
 '**Event Sourcing:**\n시스템의 현재 상태를 저장하는 대신, 상태를 만들어낸 이벤트의 시퀀스를 저장하는 패턴.\n\n**전통적 방식 vs Event Sourcing:**\n```\n// 전통적: 현재 상태만 저장\norders 테이블: { id: 1, status: "SHIPPED", amount: 50000 }\n\n// Event Sourcing: 이벤트 시퀀스 저장\nevent_store:\n1. OrderCreated  { orderId: 1, amount: 50000, time: T1 }\n2. PaymentConfirmed { orderId: 1, time: T2 }\n3. ItemShipped { orderId: 1, trackingNo: "ABC", time: T3 }\n\n현재 상태 = 이벤트 1 + 2 + 3을 순서대로 적용\n```\n\n**장점:**\n1. **완전한 감사 로그**: 모든 상태 변경 이력 보존\n2. **시간 여행 (Time Travel)**: 특정 시점의 상태 재현 가능\n3. **이벤트 재처리**: 새 기능 추가 시 기존 이벤트로 새 뷰 생성\n4. **CQRS와 자연스러운 결합**: 이벤트 → 여러 Read Model 생성\n5. **디버깅 용이**: "언제 무슨 이유로 상태가 바뀌었는가" 명확\n\n**단점:**\n1. **쿼리 복잡도**: 현재 상태 조회 시 이벤트 재생 필요 → Snapshot 패턴으로 완화\n2. **이벤트 스키마 변경 어려움**: 기존 이벤트와 호환성 유지 필요\n3. **학습 곡선**: 전통적 CRUD와 다른 사고방식 필요\n4. **저장 공간 증가**: 이벤트가 누적될수록 저장소 크기 증가\n\n**Snapshot 패턴:**\n```\nN개 이벤트마다 현재 상태를 스냅샷으로 저장\n→ 최근 스냅샷 + 이후 이벤트만 재생하면 됨\n```\n\n**적합한 도메인:** 금융 거래, 주문/재고 관리, 감사 추적이 중요한 시스템',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'Kafka의 Lag(컨슈머 지연)이란 무엇이고 어떻게 모니터링하나요?', '메시지큐',
 '**Consumer Lag:**\nProducer가 생산한 최신 오프셋과 Consumer가 처리한 오프셋의 차이.\nLag이 클수록 Consumer가 메시지 처리를 따라가지 못하고 있음을 의미.\n\n```\n파티션 상태:\nLatest Offset (Producer 최신): 10000\nCurrent Offset (Consumer 처리): 9500\nLag = 10000 - 9500 = 500\n```\n\n**Lag 발생 원인:**\n1. Consumer 처리 속도 < 메시지 생산 속도\n2. Consumer 장애 또는 중단\n3. 특정 파티션의 Rebalancing\n4. Consumer 로직의 외부 의존성(DB, API) 병목\n\n**Lag 모니터링 방법:**\n\n**Kafka CLI:**\n```bash\nkafka-consumer-groups.sh \\\n  --bootstrap-server localhost:9092 \\\n  --group my-consumer-group \\\n  --describe\n\nGROUP  TOPIC  PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG\nmy-grp orders 0          9500            10000           500\n```\n\n**Prometheus + Kafka Exporter:**\n```\nkafka_consumergroup_lag{topic="orders", partition="0"} 500\n```\n\n**Grafana 대시보드로 시각화 + 임계치 알림 설정**\n\n**Lag 해결 방법:**\n1. **Consumer 수 증가** (파티션 수 이내)\n2. **파티션 수 증가** (Consumer도 함께 증가)\n3. **Consumer 로직 최적화** (배치 처리, DB 쿼리 최적화)\n4. **메시지 처리 비동기화** (처리를 백그라운드로)\n\n**운영 기준:**\n- Lag이 점진적 증가 → Consumer 수 부족\n- Lag이 특정 시간대에만 급증 → 트래픽 패턴 분석\n- 임계치(예: 10000) 초과 시 알림 설정 권장',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'CQRS(Command Query Responsibility Segregation) 패턴이란 무엇인가요?', '메시지큐',
 '**CQRS:**\n명령(Command, 쓰기)과 조회(Query, 읽기)의 책임을 분리하는 아키텍처 패턴.\n\n**기존 방식 (단일 모델):**\n```\n[클라이언트]\n    ↓ 읽기/쓰기 동일 모델\n[서비스]\n    ↓\n[단일 DB]\n// 읽기/쓰기 최적화 충돌, 복잡한 조회 쿼리와 도메인 모델 충돌\n```\n\n**CQRS 구조:**\n```\n[클라이언트]\n    ├── Command (쓰기) → [Command Handler] → [Write DB (정규화)]\n    │                                              ↓ 이벤트 발행\n    └── Query (읽기)  ← [Query Handler]  ← [Read DB (역정규화, 뷰 최적화)]\n```\n\n**Command 측 (쓰기 최적화):**\n```java\n// 도메인 규칙에 집중, 정규화된 모델\npublic class CreateOrderCommand {\n    private Long userId;\n    private List<OrderItem> items;\n}\n// MySQL - 정규화된 스키마\n```\n\n**Query 측 (읽기 최적화):**\n```java\n// 뷰에 최적화된 Flat 구조\npublic class OrderSummaryView {\n    private Long orderId;\n    private String userName;    // 사용자 테이블 JOIN 결과 미리 저장\n    private String productName; // 상품 테이블 JOIN 결과\n    private Integer totalAmount;\n}\n// Elasticsearch 또는 역정규화된 MySQL 뷰 테이블\n```\n\n**장점:**\n1. 읽기/쓰기 독립 최적화 및 확장\n2. 복잡한 쿼리 단순화\n3. 읽기 성능 대폭 향상 가능\n\n**단점:**\n1. 결과적 일관성 (Eventual Consistency) — 쓰기 후 읽기 모델 갱신에 시간 차이\n2. 구현 복잡도 증가\n3. 데이터 중복 저장\n\n**Event Sourcing과 CQRS:**\n둘은 자주 함께 사용되지만 독립적 패턴 — CQRS만 사용해도 충분한 경우 많음.',
 'MODEL_ANSWER', TRUE, NOW());

-- ============================================================
-- 마이크로서비스 (6문항)
-- ============================================================

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'Saga 패턴이란 무엇이고 분산 트랜잭션을 어떻게 처리하나요?', '마이크로서비스',
 '**문제 상황:**\n마이크로서비스에서는 각 서비스가 독립 DB를 가지므로, 여러 서비스에 걸친 트랜잭션을 DB 레벨에서 처리할 수 없습니다.\n\n**Saga 패턴:**\n분산 트랜잭션을 여러 개의 로컬 트랜잭션 + 보상 트랜잭션(Compensating Transaction)으로 처리하는 패턴.\n\n**Choreography-based Saga (이벤트 기반):**\n```\n[주문 서비스]\n→ 주문 생성 → OrderCreated 이벤트 발행\n\n[재고 서비스]\n→ OrderCreated 수신 → 재고 차감 → StockReserved 이벤트\n\n[결제 서비스]\n→ StockReserved 수신 → 결제 처리 → PaymentCompleted 이벤트\n\n// 결제 실패 시 보상:\n→ PaymentFailed 이벤트 → [재고 서비스] 재고 복원 → [주문 서비스] 주문 취소\n```\n\n**장점:** 느슨한 결합, 중앙 코디네이터 없음\n**단점:** 이벤트 흐름 추적 어려움, 순환 이벤트 위험\n\n**Orchestration-based Saga (코디네이터 기반):**\n```\n[Saga Orchestrator]\n1. → 재고 서비스에 차감 요청\n2. ← 성공\n3. → 결제 서비스에 결제 요청\n4. ← 실패\n5. → 재고 서비스에 복원 요청 (보상)\n6. → 주문 서비스에 취소 요청 (보상)\n```\n\n**장점:** 흐름이 한 곳에 집중, 디버깅 쉬움\n**단점:** Orchestrator가 SPOF 가능성\n\n**보상 트랜잭션 설계 원칙:**\n- 각 로컬 트랜잭션마다 보상 트랜잭션 정의 필수\n- 보상도 실패할 수 있음 → 재시도 + DLQ 처리',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', '서비스 메시(Service Mesh)란 무엇이고 어떤 문제를 해결하나요?', '마이크로서비스',
 '**서비스 메시:**\n마이크로서비스 간의 통신을 관리하는 전용 인프라 계층. 사이드카 프록시(Sidecar Proxy) 패턴으로 각 서비스 옆에 프록시를 배치.\n\n**사이드카 패턴:**\n```\n[서비스 A]─[Envoy 프록시]\n                ↓ 모든 트래픽 통과\n           [서비스 메시 컨트롤 플레인 (Istio)]\n                ↓\n[서비스 B]─[Envoy 프록시]\n```\n\n**서비스 메시가 해결하는 문제:**\n\n**1. 서비스 디스커버리 & 로드밸런싱:**\n코드 변경 없이 자동 처리\n\n**2. 상호 TLS (mTLS):**\n서비스 간 통신 자동 암호화 → 코드 변경 없이 제로 트러스트 보안\n\n**3. 분산 트레이싱:**\n```\n요청 → [서비스 A 프록시] → [서비스 B 프록시] → [서비스 C 프록시]\n                ↓               ↓               ↓\n         [트레이스 수집] [트레이스 수집] [트레이스 수집]\n                        ↓\n                   [Jaeger/Zipkin 시각화]\n```\n\n**4. 트래픽 관리:**\n- 카나리 배포 (5% 신규, 95% 기존)\n- Circuit Breaker\n- Retry 및 타임아웃 설정\n\n**대표 솔루션:**\n- **Istio**: 가장 풍부한 기능, 복잡도 높음\n- **Linkerd**: 경량, 성능 중심\n- **AWS App Mesh**: AWS 네이티브\n\n**단점:**\n- 사이드카로 인한 리소스 오버헤드 (CPU, 메모리)\n- 운영 복잡도 증가\n- 학습 곡선 높음\n\n**도입 시점:** 10개 이상의 서비스, 보안/관찰 가능성 요구가 높을 때',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', '마이크로서비스에서 분산 트레이싱(Distributed Tracing)은 어떻게 구현하나요?', '마이크로서비스',
 '**문제 상황:**\n단일 요청이 여러 서비스를 거칠 때, 어느 서비스에서 얼마나 시간이 걸리는지, 어디서 오류가 발생했는지 파악이 어렵습니다.\n\n```\n클라이언트 → [API GW] → [주문 서비스] → [재고 서비스] → [결제 서비스]\n어느 서비스에서 500ms가 걸렸는가? 어디서 오류났는가?\n```\n\n**분산 트레이싱 핵심 개념:**\n\n**Trace:** 요청의 전체 흐름 (루트 트레이스 ID)\n**Span:** 각 서비스 내의 작업 단위 (부모-자식 관계)\n```\nTrace ID: abc-123\n├── Span: API Gateway (10ms)\n├── Span: Order Service (50ms)\n│   ├── Span: DB Query (30ms)\n│   └── Span: Cache Lookup (5ms)\n└── Span: Payment Service (40ms)\n```\n\n**구현 방법 (Spring Boot):**\n```xml\n<!-- Micrometer Tracing + Zipkin -->\n<dependency>\n    <groupId>io.micrometer</groupId>\n    <artifactId>micrometer-tracing-bridge-brave</artifactId>\n</dependency>\n<dependency>\n    <groupId>io.zipkin.reporter2</groupId>\n    <artifactId>zipkin-reporter-brave</artifactId>\n</dependency>\n```\n\n```yaml\n# application.yml\nmanagement:\n  tracing:\n    sampling:\n      probability: 1.0  # 100% 샘플링 (운영은 0.1 권장)\nspring:\n  zipkin:\n    base-url: http://zipkin:9411\n```\n\n**HTTP 헤더로 컨텍스트 전파:**\n```\nX-B3-TraceId: abc-123\nX-B3-SpanId: def-456\nX-B3-ParentSpanId: abc-789\n```\n\n**주요 도구:**\n- Zipkin (가볍고 단순)\n- Jaeger (Uber 오픈소스, 더 풍부한 UI)\n- AWS X-Ray (AWS 환경)\n\n**운영 팁:** 샘플링 비율을 1~10%로 설정하여 성능 영향 최소화',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'Strangler Fig 패턴이란 무엇이고 모놀리스 마이그레이션에서 어떻게 활용하나요?', '마이크로서비스',
 '**Strangler Fig (스트랭글러 피그):**\n나무를 감고 자라며 결국 숙주 나무를 대체하는 무화과나무에서 이름을 딴 점진적 마이그레이션 패턴.\n모놀리식 시스템을 한 번에 재작성하지 않고, 기능을 하나씩 신규 서비스로 이전하는 방식.\n\n**동작 방식:**\n```\n1단계: 모놀리스 앞에 프록시/파사드 배치\n[클라이언트] → [Strangler Facade]\n                    ↓ 모든 요청\n              [모놀리스 (기존)]\n\n2단계: 특정 기능을 신규 서비스로 추출\n[클라이언트] → [Strangler Facade]\n                    ├─ /users/* → [신규 User Service]\n                    └─ 나머지   → [모놀리스]\n\n3단계: 점진적으로 기능 이전\n[클라이언트] → [API Gateway]\n                    ├─ /users/*   → [User Service]\n                    ├─ /orders/*  → [Order Service]\n                    └─ 나머지     → [모놀리스 (축소 중)]\n\n4단계: 모놀리스 완전히 대체 또는 소멸\n```\n\n**이전 우선순위 결정 기준:**\n- 독립적으로 배포해야 하는 기능\n- 다른 팀이 담당하는 기능\n- 확장성이 필요한 기능\n- 기술 부채가 집중된 기능\n\n**장점:**\n- 서비스 중단 없이 점진적 마이그레이션\n- 리스크 분산 (한 번에 전체 재작성 실패 방지)\n- 즉시 비즈니스 가치 전달\n- 롤백 용이 (파사드에서 라우팅만 변경)\n\n**단점:**\n- 두 시스템 동시 운영 비용\n- 데이터 동기화 복잡도\n- 마이그레이션 기간이 길어질 수 있음\n\n**성공 조건:** 도메인 경계가 명확할수록, 파사드 라우팅이 유연할수록 효과적',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', '마이크로서비스의 관찰 가능성(Observability) 3가지 핵심 요소를 설명해주세요.', '마이크로서비스',
 '관찰 가능성(Observability)은 시스템 내부 상태를 외부 출력(로그, 메트릭, 트레이스)으로 추론할 수 있는 능력입니다.\n\n**세 가지 기둥 (Three Pillars of Observability):**\n\n**1. Logs (로그) — "무슨 일이 있었는가?"**\n```\n구조화 로그 (JSON 형식):\n{"timestamp":"2024-01-15T10:30:00Z","level":"ERROR",\n "service":"order-service","traceId":"abc-123",\n "message":"주문 처리 실패","userId":456,"orderId":789}\n\n// 비구조화 로그 (나쁜 예): "Error occurred at line 42"\n```\n**핵심:** 구조화 로그 + 중앙 수집 (ELK Stack: Elasticsearch + Logstash + Kibana)\n\n**2. Metrics (메트릭) — "시스템이 얼마나 잘 동작하는가?"**\n```\n// 4 Golden Signals\n- Latency: 응답 시간 (P50, P95, P99)\n- Traffic: 초당 요청 수 (RPS)\n- Errors: 오류율 (%)\n- Saturation: 자원 사용률 (CPU, Memory, 큐 깊이)\n\n기술: Prometheus (수집) + Grafana (시각화)\n```\n\n**3. Traces (트레이스) — "요청이 어떤 경로로 흘렀는가?"**\n- 분산 트레이싱으로 서비스 간 요청 흐름 추적\n- Jaeger, Zipkin, AWS X-Ray\n\n**상관 관계 연결 (Correlation):**\n```\n로그의 traceId = 트레이스의 traceId\n→ 특정 요청의 로그 + 트레이스를 함께 조회 가능\n```\n\n**도구 스택 예시:**\n```\n로그: Fluentd → Elasticsearch → Kibana\n메트릭: Prometheus → Grafana (알림: Alertmanager)\n트레이스: Micrometer → Zipkin\n```\n\n**SLO/SLA 연계:**\nメトリクス 기반으로 SLO(Service Level Objective) 정의 → 위반 시 자동 알림',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'API Composition 패턴과 CQRS를 비교하고 각각 어떤 상황에서 사용하나요?', '마이크로서비스',
 '**문제 상황:**\n마이크로서비스에서 DB가 분리되어 있으면 여러 서비스의 데이터를 조합하여 조회하기 어렵습니다.\n\n---\n\n**API Composition 패턴:**\nAPI Gateway 또는 BFF(Backend for Frontend)가 여러 서비스를 호출하여 결과를 조합.\n\n```\n[클라이언트]\n    ↓ 주문 상세 조회\n[API Composer (BFF)]\n    ├─ GET /orders/1        → [Order Service]   → {orderId, status, amount}\n    ├─ GET /users/123       → [User Service]    → {name, email}\n    └─ GET /products/456    → [Product Service] → {name, image}\n    ↓ 조합\n[통합 응답 반환]\n```\n\n**장점:**\n- 구현이 상대적으로 단순\n- 데이터 동기화 불필요\n\n**단점:**\n- 동기 호출 → 레이턴시 누적 (병렬 호출로 완화)\n- 대용량 조회, 복잡한 필터링/정렬 어려움\n- 페이지네이션 구현 어려움\n\n---\n\n**CQRS (Command Query Responsibility Segregation):**\n별도의 읽기 전용 DB(Read Model)에 여러 서비스의 데이터를 이벤트 기반으로 미리 조합하여 저장.\n\n```\n[Order Service] → OrderCreated 이벤트 → [이벤트 핸들러]\n[User Service]  → UserUpdated 이벤트 → [Read Model DB 업데이트]\n[Product Service] → ProductUpdated 이벤트 ↗\n\n조회 시:\n[클라이언트] → [Query Service] → [Read Model DB (역정규화)] → 즉시 응답\n```\n\n**장점:**\n- 조회 성능 매우 뛰어남\n- 복잡한 필터링/정렬/페이지네이션 가능\n\n**단점:**\n- 결과적 일관성 (이벤트 전파 지연)\n- 구현 복잡도 높음\n\n**선택 기준:**\n| 상황 | 권장 패턴 |\n|------|----------|\n| 단순 조합, 소량 조회 | API Composition |\n| 대용량 조회, 복잡한 검색 | CQRS |\n| 실시간 일관성 필요 | API Composition |',
 'MODEL_ANSWER', TRUE, NOW());

-- ============================================================
-- 로드밸런싱 (6문항)
-- ============================================================

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', '카나리 배포(Canary Deployment)와 블루/그린 배포(Blue/Green Deployment)의 차이점은?', '로드밸런싱',
 '두 방식 모두 무중단 배포 전략이지만 트래픽 전환 방식이 다릅니다.\n\n**블루/그린 배포 (Blue/Green Deployment):**\n```\n현재 환경(Blue): [v1 서버들] ← 100% 트래픽\n신규 환경(Green): [v2 서버들] ← 배포 완료, 검증\n\n전환:\n[로드밸런서] 라우팅: Blue → Green (즉시 전환)\n이후: [v2 서버들] ← 100% 트래픽\nBlue 환경은 롤백 대비 유지\n```\n\n**특징:**\n- 즉각적인 완전 전환\n- 롤백이 즉각적 (Blue 환경으로 즉시 되돌림)\n- 두 배의 인프라 비용\n- 배포 중 이슈 발견이 늦음 (이미 100% 전환 후)\n\n---\n\n**카나리 배포 (Canary Deployment):**\n```\n[로드밸런서]\n├── 95% 트래픽 → [v1 서버들 (기존)]\n└──  5% 트래픽 → [v2 서버들 (신규)]\n\n점진적 확대:\n5% → 10% → 25% → 50% → 100%\n각 단계에서 오류율, 레이턴시 모니터링\n```\n\n**특징:**\n- 소수 사용자에게 먼저 적용 → 리스크 조기 발견\n- 점진적 확대로 영향 범위 최소화\n- A/B 테스트와 결합 가능\n- 롤백 = 트래픽 비율 0%로 설정\n\n**비교:**\n| 항목 | 블루/그린 | 카나리 |\n|------|-----------|--------|\n| 전환 속도 | 즉각 | 점진적 |\n| 리스크 발견 | 늦음 | 빠름 |\n| 인프라 비용 | 2배 | 소량 추가 |\n| 롤백 속도 | 즉각 | 즉각 (비율 0%) |\n| 복잡도 | 낮음 | 높음 |\n\n**실무 선택:**\n- 큰 변경, 빠른 롤백 필요 → 블루/그린\n- 점진적 검증 필요, 실험적 기능 → 카나리',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'Auto Scaling이란 무엇이고 Scale-Out 정책을 어떻게 설계하나요?', '로드밸런싱',
 '**Auto Scaling:**\n트래픽이나 부하에 따라 자동으로 서버 인스턴스 수를 조절하는 기능.\n\n**AWS Auto Scaling Group (ASG) 구성:**\n```\nMin: 2 (최소 인스턴스)\nDesired: 3 (기본 인스턴스)\nMax: 10 (최대 인스턴스)\n```\n\n**Scaling 정책 종류:**\n\n**1. 단계적 조정 (Step Scaling):**\n```\nCPU 50~70% → +1 인스턴스\nCPU 70~90% → +2 인스턴스\nCPU 90%+   → +3 인스턴스\n\nCPU 30~50% → -1 인스턴스\nCPU < 30%  → -2 인스턴스\n```\n\n**2. 목표 추적 (Target Tracking):**\n```\n// CPU 사용률 60% 유지를 목표\n→ CPU > 60%: 자동 Scale-Out\n→ CPU < 60%: 자동 Scale-In\n// 가장 단순하고 추천되는 방식\n```\n\n**3. 예약 스케일링 (Scheduled Scaling):**\n```\n// 이벤트/피크 시간 예측 가능할 때\n매일 09:00 → Min: 5, Desired: 8\n매일 23:00 → Min: 2, Desired: 3\n```\n\n**스케일링 설계 시 주의사항:**\n\n**쿨다운 기간 (Cooldown Period):**\n```\n스케일 아웃 후 300초 동안 추가 스케일링 금지\n→ 새 인스턴스가 워밍업되기 전에 또 스케일 아웃 방지\n```\n\n**스케일 인 보호:**\n```\n롤링 배포 중인 인스턴스는 스케일 인에서 제외\n```\n\n**올바른 메트릭 선택:**\n- CPU: 연산 집중 서비스\n- 메모리: Java 애플리케이션 (커스텀 메트릭)\n- 큐 깊이: 메시지 처리 서비스\n- 요청 수 (RPS): API 서버\n\n**인스턴스 워밍업 + 헬스 체크:**\n신규 인스턴스가 헬스 체크 통과 후 로드밸런서에 등록되도록 설정',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', '글로벌 트래픽을 처리하기 위한 지역(Region) 기반 로드밸런싱은 어떻게 설계하나요?', '로드밸런싱',
 '**글로벌 트래픽 분산의 목표:**\n- 사용자에게 지리적으로 가까운 서버로 라우팅 → 레이턴시 최소화\n- 특정 리전 장애 시 다른 리전으로 자동 페일오버\n\n**계층적 로드밸런싱 구조:**\n```\n[사용자 (한국/미국/유럽)]\n    ↓ DNS 조회\n[글로벌 DNS 로드밸런서 (GeoDNS)]\n    ├── 한국 사용자 → ap-northeast-2 (서울 리전)\n    ├── 미국 사용자 → us-east-1 (버지니아 리전)\n    └── 유럽 사용자 → eu-west-1 (아일랜드 리전)\n         ↓\n[리전별 로드밸런서 (ALB)]\n    → 각 리전의 서버 클러스터\n```\n\n**GeoDNS 동작:**\n```\n클라이언트 DNS 쿼리 → DNS 서버가 IP 감지\n→ 한국 IP → 서울 리전 IP 반환\n→ 미국 IP → 버지니아 리전 IP 반환\n```\n\n**Anycast:**\n동일 IP 주소를 여러 리전에서 서비스, 네트워크가 자동으로 가장 가까운 노드로 라우팅.\n(Cloudflare, AWS Global Accelerator에서 활용)\n\n**Active-Active vs Active-Passive:**\n```\nActive-Active: 모든 리전이 동시에 트래픽 처리\n→ 최고 성능, 높은 운영 복잡도\n\nActive-Passive: 주 리전이 처리, 보조 리전은 대기\n→ 장애 시 DNS 전환 (몇 분 소요)\n→ 비용 효율적\n```\n\n**데이터 동기화 전략:**\n- 읽기는 로컬 리전 DB에서\n- 쓰기는 글로벌 Primary로 → 각 리전에 복제\n- 또는 Active-Active DB (CockroachDB, DynamoDB Global Tables)\n\n**레이턴시 목표:**\n- 동일 리전: < 10ms\n- 인근 리전 (한국-일본): < 50ms\n- 글로벌 (한국-미국): < 200ms',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', '로드밸런서에서 커넥션 드레이닝(Connection Draining)이란 무엇인가요?', '로드밸런싱',
 '**Connection Draining (연결 비우기):**\n서버를 서비스에서 제거하거나 종료할 때, 기존에 연결된 클라이언트의 요청이 완료될 때까지 기다리는 프로세스.\n\n**Connection Draining 없을 때 문제:**\n```\n배포 또는 Scale-In 시:\n서버 즉시 종료 → 처리 중인 요청 강제 종료\n→ 클라이언트에게 오류 (503) 반환\n```\n\n**Connection Draining 있을 때:**\n```\n1. 로드밸런서가 해당 서버를 "Draining" 상태로 전환\n2. 새 요청은 다른 서버로 라우팅\n3. 기존 활성 연결은 완료까지 유지\n4. 모든 연결 완료 (또는 타임아웃) 후 서버 제거\n```\n\n**AWS ALB 설정:**\n```\nDeregistration Delay: 300초 (기본)\n→ 서버 제거 요청 후 300초 동안 기존 연결 유지\n→ 300초 내 완료 안 되면 강제 종료\n```\n\n**Spring Boot Graceful Shutdown:**\n```yaml\n# application.yml\nserver:\n  shutdown: graceful  # 활성 요청 완료 후 종료\n\nspring:\n  lifecycle:\n    timeout-per-shutdown-phase: 30s  # 최대 30초 대기\n```\n\n**Kubernetes에서의 처리:**\n```yaml\nspec:\n  terminationGracePeriodSeconds: 60  # 60초 대기\n  containers:\n  - lifecycle:\n      preStop:\n        exec:\n          command: ["/bin/sh", "-c", "sleep 5"]  # 로드밸런서 반영 대기\n```\n\n**중요성:**\n무중단 배포(Rolling, Blue/Green, Canary)의 핵심 전제 조건.\nConnection Draining 없으면 배포 중 필연적으로 사용자 오류 발생.',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', '레이트 리미팅(Rate Limiting)의 알고리즘을 비교하고 구현 방법을 설명해주세요.', '로드밸런싱',
 '**Rate Limiting 목적:**\n- API 남용/DDoS 방어\n- 공정한 리소스 분배\n- 백엔드 서비스 보호\n\n**주요 알고리즘:**\n\n**1. Fixed Window (고정 윈도우):**\n```\n1분 단위 창: [00:00~01:00] 최대 100 요청\n→ 00:59에 100번 + 01:00에 100번 = 2초에 200번 가능\n문제: 창 경계에서 버스트 트래픽 허용\n```\n\n**2. Sliding Window (슬라이딩 윈도우):**\n```\n현재 시각 기준 과거 1분을 동적으로 계산\n→ 항상 정확히 1분 내 최대 N회 보장\n구현: Redis Sorted Set + score=timestamp\n```\n\n**3. Token Bucket (토큰 버킷):**\n```\n버킷에 초당 N개 토큰 보충 (최대 M개)\n요청 1개 = 토큰 1개 소비\n버킷 비면 요청 거부\n\n장점: 버스트 트래픽 허용 (버킷에 쌓인 토큰만큼)\n```\n\n**4. Leaky Bucket (누수 버킷):**\n```\n요청을 큐에 넣고 일정 속도로만 처리\n큐가 가득 차면 거부\n\n장점: 출력 속도 일정 (스파이크 없음)\n단점: 큐 대기로 레이턴시 발생\n```\n\n**Redis 기반 구현 (Sliding Window):**\n```java\npublic boolean isAllowed(String userId, int maxRequests, long windowMs) {\n    long now = System.currentTimeMillis();\n    long windowStart = now - windowMs;\n    String key = "rate:" + userId;\n\n    // 윈도우 밖의 오래된 항목 제거\n    redisTemplate.opsForZSet().removeRangeByScore(key, 0, windowStart);\n    // 현재 요청 수 확인\n    Long count = redisTemplate.opsForZSet().zCard(key);\n    if (count < maxRequests) {\n        redisTemplate.opsForZSet().add(key, String.valueOf(now), now);\n        redisTemplate.expire(key, windowMs, TimeUnit.MILLISECONDS);\n        return true;\n    }\n    return false;\n}\n```\n\n**응답:**\n```\nHTTP 429 Too Many Requests\nRetry-After: 60\nX-RateLimit-Limit: 100\nX-RateLimit-Remaining: 0\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', '리버스 프록시(Reverse Proxy)와 포워드 프록시(Forward Proxy)의 차이점은?', '로드밸런싱',
 '**포워드 프록시 (Forward Proxy):**\n클라이언트 측에 위치하여 클라이언트를 대신해 인터넷에 요청하는 프록시.\n\n```\n[클라이언트] → [포워드 프록시] → [인터넷/서버]\n// 서버는 클라이언트의 실제 IP를 모르고 프록시 IP만 봄\n```\n\n**포워드 프록시 용도:**\n- 기업 내부 인터넷 접근 통제\n- 특정 사이트 차단/허용 정책\n- 클라이언트 익명성 (VPN 유사)\n- 캐싱으로 대역폭 절약\n\n---\n\n**리버스 프록시 (Reverse Proxy):**\n서버 측에 위치하여 클라이언트 요청을 대신 받아 내부 서버로 전달하는 프록시.\n\n```\n[클라이언트] → [리버스 프록시 (Nginx)] → [내부 서버들]\n// 클라이언트는 내부 서버의 실제 IP를 모름\n```\n\n**리버스 프록시 용도:**\n1. **로드밸런싱**: 요청을 여러 서버에 분산\n2. **SSL 종료**: HTTPS → HTTP 변환 (인증서 한 곳에서 관리)\n3. **캐싱**: 정적 콘텐츠 캐시\n4. **압축**: gzip 압축 적용\n5. **보안**: 내부 서버 IP 숨기기, WAF(Web Application Firewall)\n6. **라우팅**: URL 기반 서비스 라우팅\n\n**Nginx 리버스 프록시 설정:**\n```nginx\nserver {\n    listen 443 ssl;\n    ssl_certificate /path/to/cert.pem;\n\n    location /api/ {\n        proxy_pass http://backend-servers;\n    }\n\n    location /static/ {\n        root /var/www;\n    }\n}\n\nupstream backend-servers {\n    server 10.0.1.1:8080 weight=3;\n    server 10.0.1.2:8080 weight=1;\n}\n```\n\n**요약:**\n- 포워드 프록시: 클라이언트를 위한 중개자 (클라이언트 측)\n- 리버스 프록시: 서버를 위한 중개자 (서버 측)\n- 현대 웹 인프라에서는 Nginx/HAProxy가 리버스 프록시로 필수 사용',
 'MODEL_ANSWER', TRUE, NOW());

-- ============================================================
-- API설계 (6문항)
-- ============================================================

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'GraphQL과 REST API의 차이점과 각각 언제 사용하는 것이 좋은지 설명해주세요.', 'API설계',
 '**REST API:**\n리소스 중심의 여러 엔드포인트로 구성된 API.\n\n```\nGET /users/1           → 사용자 전체 필드\nGET /users/1/orders    → 주문 목록\nGET /products/1        → 상품 정보\n// 3번의 요청 필요\n```\n\n**GraphQL:**\n클라이언트가 필요한 데이터 구조를 직접 쿼리로 정의하는 단일 엔드포인트 API.\n\n```graphql\n# 한 번의 요청으로 필요한 데이터만\nquery {\n  user(id: 1) {\n    name\n    orders {\n      id\n      product {\n        name\n        price\n      }\n    }\n  }\n}\n```\n\n**REST의 문제점:**\n- Over-fetching: 필요 없는 필드도 모두 받음\n- Under-fetching: N개 리소스 → N번 요청\n- 화면마다 다른 엔드포인트 필요 (API 버전 증가)\n\n**GraphQL의 문제점:**\n- N+1 쿼리 문제 → DataLoader 패턴으로 해결\n- 캐싱이 복잡 (POST 요청이 주)\n- 파일 업로드 처리 복잡\n- 쿼리 복잡도 제한 필요 (DoS 방어)\n- 학습 곡선\n\n**비교:**\n| 항목 | REST | GraphQL |\n|------|------|---------|\n| 엔드포인트 | 다수 | 단일 (/graphql) |\n| 데이터 제어 | 서버 | 클라이언트 |\n| 오버패칭 | 있음 | 없음 |\n| 캐싱 | 쉬움 (HTTP) | 복잡 |\n| 학습 곡선 | 낮음 | 높음 |\n\n**언제 REST:**\n- 단순한 CRUD, 외부 공개 API, 캐싱 중요\n\n**언제 GraphQL:**\n- 다양한 클라이언트(웹/앱/IoT), 복잡한 데이터 그래프, BFF 패턴',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'JWT(JSON Web Token)의 구조와 Refresh Token 전략을 설명해주세요.', 'API설계',
 '**JWT 구조:**\n```\nHeader.Payload.Signature\n\n// 예시\neyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEyMywicm9sZSI6IlVTRVIiLCJleHAiOjE3MDAwMDAwMDB9.abc123\n\nHeader: { "alg": "HS256", "typ": "JWT" }\nPayload: { "userId": 123, "role": "USER", "exp": 1700000000 }\nSignature: HMACSHA256(base64(Header) + "." + base64(Payload), secretKey)\n```\n\n**Access Token + Refresh Token 전략:**\n\n```\n[로그인]\n→ Access Token (유효기간: 15분)\n→ Refresh Token (유효기간: 7일, DB/Redis에 저장)\n\n[API 요청]\nAuthorization: Bearer {access_token}\n→ 정상: 처리\n→ 401 (만료): Refresh Token으로 재발급\n\n[토큰 재발급]\nPOST /auth/refresh { refreshToken: "..." }\n→ DB에서 Refresh Token 검증\n→ 유효하면 새 Access Token 발급\n→ Refresh Token Rotation 적용 시 새 Refresh Token도 발급\n```\n\n**Refresh Token Rotation:**\n```\nRefresh Token 사용 시 → 기존 토큰 무효화 + 새 토큰 발급\n탈취 감지: 무효화된 토큰으로 재요청 시 → 전체 세션 강제 만료\n```\n\n**보안 고려사항:**\n```\n// Access Token: 메모리에 저장 (XSS 방어)\n// Refresh Token: HttpOnly Cookie (XSS 방어, CSRF는 SameSite로 방어)\n\nSet-Cookie: refreshToken=xxx; HttpOnly; Secure; SameSite=Strict; Path=/auth/refresh\n```\n\n**JWT 단점:**\n- 서버에서 토큰 즉시 무효화 불가 (만료 전까지 유효)\n- Payload 크기로 매 요청 오버헤드\n- 해결: 블랙리스트 (Redis에 무효화 토큰 목록)',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'Webhook과 Polling의 차이점과 각각의 장단점은?', 'API설계',
 '**Polling (폴링):**\n클라이언트가 서버에 주기적으로 요청하여 변경 사항을 확인하는 방식.\n\n```\n[클라이언트]\n→ 매 30초: GET /notifications/new → "없음"\n→ 매 30초: GET /notifications/new → "없음"\n→ 매 30초: GET /notifications/new → "3개 있음"\n```\n\n**Short Polling 단점:**\n- 변화가 없어도 지속적 요청 → 서버 부하\n- 이벤트와 감지 사이의 지연 (폴링 주기만큼)\n\n**Long Polling (개선된 폴링):**\n```\n→ GET /notifications/new\n← 새 이벤트 없으면 연결 유지 (최대 30초)\n← 이벤트 발생 시 즉시 응답 → 클라이언트 즉시 수신\n```\n단점: 연결 유지로 서버 리소스 소비\n\n---\n\n**Webhook:**\n이벤트 발생 시 서버가 미리 등록된 클라이언트 URL로 능동적으로 HTTP 요청.\n\n```\n1. 클라이언트가 Webhook URL 등록\n   POST /webhooks { url: "https://my-server.com/webhook" }\n\n2. 이벤트 발생 시 서버가 등록 URL로 POST 요청\n   POST https://my-server.com/webhook\n   { event: "payment.completed", data: {...} }\n\n3. 클라이언트가 즉시 처리\n```\n\n**비교:**\n| 항목 | Polling | Webhook |\n|------|---------|--------|\n| 방향 | 클라이언트 → 서버 | 서버 → 클라이언트 |\n| 실시간성 | 낮음 (주기 지연) | 높음 (즉시) |\n| 서버 부하 | 높음 | 낮음 |\n| 클라이언트 조건 | 없음 | 공개 URL 필요 |\n| 재시도 복잡도 | 낮음 | 높음 |\n\n**Webhook 주의사항:**\n- 클라이언트 응답 타임아웃 처리 (보통 200 OK 즉시 반환 후 비동기 처리)\n- 실패 시 재시도 로직 필요\n- 시그니처 검증으로 위조 방지',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'API 멱등성(Idempotency)이 중요한 이유와 구현 방법을 설명해주세요.', 'API설계',
 '**멱등성 (Idempotency):**\n동일한 요청을 여러 번 실행해도 결과가 동일한 성질.\n\n**왜 중요한가:**\n네트워크 오류, 타임아웃, 클라이언트 재시도 등으로 동일 요청이 중복으로 서버에 도달할 수 있습니다.\n```\n결제 요청 → [타임아웃] → 클라이언트 재시도\n→ 서버에 두 번 도달 → 중복 결제 발생 (멱등성 없으면)\n```\n\n**HTTP 메서드별 멱등성:**\n```\nGET, HEAD, OPTIONS: 멱등성 O (읽기 전용)\nPUT, DELETE: 멱등성 O (동일 결과 보장)\nPOST: 멱등성 X (기본) → 별도 구현 필요\nPATCH: 일반적으로 X (경우에 따라 다름)\n```\n\n**POST에서 멱등성 구현 — Idempotency Key:**\n```\n클라이언트: 고유한 Idempotency-Key 생성 (UUID)\nPOST /payments\nIdempotency-Key: 550e8400-e29b-41d4-a716-446655440000\n{ amount: 50000, ... }\n```\n\n**서버 처리:**\n```java\n@PostMapping("/payments")\npublic ResponseEntity<Payment> createPayment(\n    @RequestHeader("Idempotency-Key") String idempotencyKey,\n    @RequestBody PaymentRequest req\n) {\n    // Redis에서 이미 처리된 키인지 확인\n    String cached = redis.get("idem:" + idempotencyKey);\n    if (cached != null) {\n        return ResponseEntity.ok(parsePayment(cached)); // 캐시된 결과 반환\n    }\n\n    Payment payment = paymentService.process(req);\n\n    // 처리 결과 저장 (24시간)\n    redis.setex("idem:" + idempotencyKey, 86400, serialize(payment));\n    return ResponseEntity.status(201).body(payment);\n}\n```\n\n**Idempotency Key 전략:**\n- 클라이언트가 UUID v4 생성\n- 동일 요청 재시도 시 같은 키 사용\n- 서버는 24시간 보관 후 만료\n- Stripe, Braintree 등 결제 API에서 표준으로 사용',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'API 게이트웨이에서 인증을 중앙화할 때의 장단점과 설계 방법은?', 'API설계',
 '**중앙화된 인증 (API Gateway 레벨):**\n모든 API 요청의 인증/인가를 API Gateway에서 처리하고, 검증된 요청만 내부 서비스로 전달.\n\n**구조:**\n```\n[클라이언트]\n    ↓ Authorization: Bearer {JWT}\n[API Gateway]\n    1. JWT 서명 검증\n    2. 토큰 만료 확인\n    3. 사용자 정보 추출\n    ↓ X-User-Id: 123, X-User-Role: USER (헤더로 전달)\n[내부 마이크로서비스]\n    → 헤더에서 사용자 정보 신뢰하여 사용\n    → 추가 JWT 검증 불필요\n```\n\n**장점:**\n1. 인증 로직 중복 제거 (서비스별 JWT 검증 코드 불필요)\n2. 인증 정책 변경 시 Gateway만 수정\n3. 내부 서비스 간 통신은 인증 오버헤드 없음\n4. 인증 관련 모니터링/로깅 중앙화\n\n**단점:**\n1. Gateway 장애 시 모든 서비스 인증 불가 → HA 필수\n2. 세분화된 권한 제어(인가)는 각 서비스에서 별도 처리 필요\n3. 내부 서비스가 헤더를 무조건 신뢰 → 내부망 보안 중요\n\n**세분화된 인가는 서비스 레벨에서:**\n```java\n// Gateway: 인증 (이 사용자가 누구인가)\n// 서비스: 인가 (이 사용자가 이 리소스에 접근 가능한가)\n@PreAuthorize("hasRole(''ADMIN'') or #userId == authentication.principal.id")\npublic Order getOrder(Long orderId, Long userId) { ... }\n```\n\n**내부 서비스 간 인증 (Service-to-Service):**\n```\n방법 1: 고정 API Key (간단, 보안 취약)\n방법 2: mTLS (상호 인증, 서비스 메시에서 자동화)\n방법 3: Short-lived JWT (서비스 계정 토큰)\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, category, model_answer, reference_type, is_active, created_at) VALUES
('MID:SYSTEM_DESIGN', 'API 하위 호환성(Backward Compatibility)을 유지하는 설계 원칙은?', 'API설계',
 '**하위 호환성이 중요한 이유:**\nAPI를 변경할 때 기존 클라이언트(모바일 앱, 파트너 서비스)가 오작동하면 안 됩니다. 특히 모바일 앱은 모든 사용자가 즉시 업데이트하지 않습니다.\n\n**Breaking Change (호환성 파괴):**\n```\n// 다음은 반드시 버전 업이 필요\n1. 필드 삭제 또는 이름 변경\n   { "userName": "...", }  →  { "name": "..." } ← 기존 클라이언트 파싱 오류\n\n2. 필수 요청 필드 추가\n   기존: POST /orders { productId, quantity }\n   변경: POST /orders { productId, quantity, region } ← 기존 요청 실패\n\n3. 응답 타입 변경\n   "price": 1000  →  "price": "1000" ← 타입 오류\n\n4. 상태 코드 변경\n   200 → 201 ← 클라이언트 분기 오류\n```\n\n**Non-Breaking Change (안전한 변경):**\n```\n// 버전 업 없이 가능\n1. 선택적 응답 필드 추가 (새 필드 무시 가능)\n   기존: { "id": 1, "name": "상품" }\n   변경: { "id": 1, "name": "상품", "category": "전자" } ✅\n\n2. 새 엔드포인트 추가\n3. 선택적 요청 파라미터 추가 (기본값 있음)\n4. 에러 메시지 변경 (코드는 유지)\n```\n\n**Consumer-Driven Contract Testing:**\n```\nPact 라이브러리: Consumer가 기대하는 응답을 계약으로 정의\n→ Provider 변경 시 계약 위반 자동 감지\n```\n\n**Field Deprecation 전략:**\n```json\n// 삭제 전 Deprecation 단계\n{\n  "user_name": "홍길동",      // deprecated, v3에서 제거 예정\n  "userName": "홍길동"        // 새 필드\n}\n// 마이그레이션 기간(3~6개월) 후 구 필드 제거\n```\n\n**Sunset 헤더:**\n```\nSunset: Sat, 31 Dec 2024 23:59:59 GMT\nDeprecation: Mon, 01 Jan 2024 00:00:00 GMT\n```',
 'MODEL_ANSWER', TRUE, NOW());
