-- SENIOR SYSTEM DESIGN 질문 Pool 시딩 (30문항: 캐싱6, 메시지큐6, 마이크로서비스6, 로드밸런싱6, API설계6)
-- referenceType: MODEL_ANSWER (상세 기술 모범답변)
-- V20 이후 스키마 기준 (question_order, evaluation_criteria, follow_up_strategy, quality_score 컬럼 없음)

-- ============================================================
-- 캐싱 (6문항)
-- ============================================================

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '대규모 트래픽을 처리하는 다계층 캐싱(Multi-Layer Caching) 전략을 설계해주세요.', '대규모 트래픽을 처리하는 다계층 캐싱(Multi-Layer Caching) 전략을 설계해주세요.', '캐싱',
 '**다계층 캐싱 구조:**\n```\n[클라이언트]\n   ↓ CDN Miss\n[CDN (CloudFront/Cloudflare)]  — 정적 콘텐츠, 엣지 캐싱\n   ↓ CDN Miss\n[API Gateway / Nginx]           — 응답 캐싱 (Proxy Cache)\n   ↓ Miss\n[애플리케이션 로컬 캐시]          — Caffeine (JVM 인메모리)\n   ↓ Miss\n[분산 캐시 (Redis Cluster)]      — 공유 캐시\n   ↓ Miss\n[DB Read Replica]               — 읽기 전용 복제본\n   ↓ Miss\n[Primary DB]                    — 원본 데이터\n```\n\n**계층별 특성:**\n| 계층 | 레이턴시 | 용량 | 비용 | TTL |\n|------|---------|------|------|-----|\n| 로컬 캐시 | < 1ms | 수백MB | 낮음 | 수십초 |\n| Redis | 1~5ms | 수십GB | 중간 | 수분~시간 |\n| CDN | 5~50ms | 무제한 | 낮음 | 수시간~일 |\n\n**로컬 캐시 + Redis 2계층 예시:**\n```java\n// L1: Caffeine (로컬) + L2: Redis\n@Cacheable(cacheNames = "products", cacheManager = "localCacheManager")\npublic Product getFromLocal(Long id) { ... }\n\n// L1 Miss → L2 조회\npublic Product getProduct(Long id) {\n    Product p = localCache.get(id);\n    if (p == null) {\n        p = redis.get("product:" + id);\n        if (p == null) {\n            p = repository.findById(id);\n            redis.set("product:" + id, p, 300);\n        }\n        localCache.put(id, p); // L1에도 저장\n    }\n    return p;\n}\n```\n\n**무효화 전략:**\n- DB 변경 → Redis 즉시 삭제 → 로컬 캐시는 짧은 TTL로 자연 만료\n- 또는 Redis Pub/Sub으로 모든 인스턴스 로컬 캐시 동시 무효화\n\n**핵심 원칙:**\n- 각 계층에 적합한 데이터 유형 배치\n- 계층이 많을수록 무효화 복잡도 증가 → 단순성과 성능의 트레이드오프',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '캐시 일관성 모델(Strong/Eventual/Weak)을 비즈니스 요구사항에 따라 어떻게 선택하나요?', '캐시 일관성 모델(Strong/Eventual/Weak)을 비즈니스 요구사항에 따라 어떻게 선택하나요?', '캐싱',
 '**일관성 수준 정의:**\n\n**Strong Consistency (강한 일관성):**\n쓰기 후 즉시 최신 데이터 보장. 모든 읽기가 최신 쓰기 반영.\n```\n재고 차감 → 즉시 캐시 업데이트 → 다음 읽기는 정확한 재고 반환\n구현: Write-Through + 동기 캐시 무효화\n비용: 높은 레이턴시, 낮은 가용성\n```\n\n**Eventual Consistency (결과적 일관성):**\n일정 시간 후 최신 데이터로 수렴. 일시적 불일치 허용.\n```\n상품 설명 업데이트 → 몇 초~분 후 캐시 갱신\n구현: 이벤트 기반 캐시 갱신, 짧은 TTL\n비용: 낮은 레이턴시, 높은 가용성\n```\n\n**Weak Consistency (약한 일관성):**\n최신 데이터 보장 없음. TTL 만료까지 오래된 데이터 반환 가능.\n```\n추천 알고리즘 결과, 통계 집계\n구현: 긴 TTL, 백그라운드 갱신\n비용: 매우 낮은 레이턴시, 높은 가용성\n```\n\n**비즈니스별 선택 매트릭스:**\n| 데이터 | 일관성 수준 | 이유 |\n|--------|------------|------|\n| 잔액/재고 | Strong | 오차 시 직접적 손해 |\n| 사용자 프로필 | Eventual | 몇 초 지연 허용 가능 |\n| 상품 이미지 | Weak | 변경 빈도 낮음 |\n| 추천/피드 | Weak | 정확도보다 속도 |\n| 주문 상태 | Eventual | 수초 지연 허용 |\n\n**CAP 정리와의 연관:**\n```\n네트워크 파티션 발생 시:\n→ Strong Consistency 선택: 가용성 포기 (CP 시스템)\n→ Eventual Consistency 선택: 일관성 잠시 포기 (AP 시스템)\n```\n\n**실무 권장:** 대부분의 데이터는 Eventual로 충분. Strong은 금전/재고 등 손실이 직접적인 경우만.',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '핫 키(Hot Key) 문제란 무엇이고 Redis에서 어떻게 해결하나요?', '핫 키(Hot Key) 문제란 무엇이고 레디스에서 어떻게 해결하나요?', '캐싱',
 '**Hot Key 문제:**\n특정 캐시 키에 트래픽이 극도로 집중되어 해당 Redis 노드가 병목이 되는 현상.\n\n```\n예: 유명 연예인 프로필 조회 → 초당 수만 번\n→ Redis Cluster에서 해당 키가 있는 노드에만 부하 집중\n→ 다른 노드는 유휴, 해당 노드만 CPU/네트워크 과부하\n```\n\n**해결 방법:**\n\n**1. 로컬 캐시 (JVM 레벨):**\n```java\n// 각 서버 인스턴스에서 로컬 캐시로 Redis 호출 분산\nLoadingCache<String, User> localCache = Caffeine.newBuilder()\n    .maximumSize(1000)\n    .expireAfterWrite(10, TimeUnit.SECONDS) // 짧은 TTL\n    .build(key -> redisService.get(key));\n```\n- Redis 요청 수 = 서버 인스턴스 수만큼만 → 부하 분산\n\n**2. 키 샤딩 (Key Sharding/Splitting):**\n```\n// 동일 데이터를 여러 키에 복제\nuser:profile:1:shard_0\nuser:profile:1:shard_1\nuser:profile:1:shard_2\n\n// 읽기 시 랜덤 샤드 선택\nint shard = random.nextInt(3);\nredis.get("user:profile:1:shard_" + shard);\n```\n- 쓰기 시 모든 샤드 동시 업데이트 필요\n\n**3. 읽기 전용 복제본 (Read Replica):**\n```\n[Primary] ─ 쓰기\n[Replica1] ─ 읽기 1/3\n[Replica2] ─ 읽기 1/3\n[Replica3] ─ 읽기 1/3\n```\n\n**4. CDN 활용:**\n- 공개 데이터(상품 정보, 이미지)는 CDN 엣지에 캐싱\n- Redis 호출 자체를 CDN이 차단\n\n**5. Consistent Hashing + 가상 노드:**\n- 노드 추가 시 최소한의 키 재분배\n- Hot Key 가능성 있는 키를 수동으로 다른 노드에 배치\n\n**모니터링:**\n```bash\n# Redis Hot Key 감지\nredis-cli --hotkeys\n# 또는 Keyspace Notifications로 접근 빈도 추적\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '캐시를 활용한 세션 관리 아키텍처를 설계하고 보안 고려사항을 설명해주세요.', '캐시를 활용한 세션 관리 아키텍처를 설계하고 보안 고려사항을 설명해주세요.', '캐싱',
 '**세션 관리 방식 비교:**\n\n**1. 서버 로컬 세션 (전통적):**\n```\n문제: 로드밸런서 환경에서 서버 재시작 또는 다른 서버로 요청 시 세션 손실\n→ Sticky Session 필요 → 로드밸런싱 비효율\n```\n\n**2. Redis 기반 중앙 세션:**\n```\n[서버1] [서버2] [서버3]\n    ↓       ↓       ↓\n    [Redis 세션 저장소]\n// 모든 서버가 동일한 세션 접근\n```\n\n**Spring Session + Redis 구성:**\n```java\n@Configuration\n@EnableRedisHttpSession(maxInactiveIntervalInSeconds = 1800)\npublic class SessionConfig {\n    @Bean\n    public RedisConnectionFactory redisConnectionFactory() {\n        return new LettuceConnectionFactory("redis-host", 6379);\n    }\n}\n// application.yml\nspring.session.store-type: redis\nspring.session.timeout: 30m\n```\n\n**세션 키 구조:**\n```\nspring:session:sessions:{sessionId}\n├── lastAccessedTime\n├── maxInactiveInterval\n├── creationTime\n└── sessionAttr:SPRING_SECURITY_CONTEXT → 인증 정보\n```\n\n**보안 고려사항:**\n\n**1. 세션 ID 보안:**\n```\n- 128비트 이상 무작위 생성 (UUID v4)\n- HttpOnly + Secure + SameSite=Strict 쿠키\n- HTTPS 전용 전송\n```\n\n**2. 세션 고정 공격 방지:**\n```java\n// 로그인 성공 시 새 세션 ID 발급\nrequest.getSession().invalidate();\nrequest.getSession(true); // 새 세션 생성\n```\n\n**3. 동시 세션 제한:**\n```java\n// Spring Security: 동시 로그인 1개만 허용\nhttpSecurity.sessionManagement()\n    .maximumSessions(1)\n    .maxSessionsPreventsLogin(false); // 새 로그인이 기존 세션 만료\n```\n\n**4. Redis 세션 암호화:**\n- 세션 데이터에 민감 정보 최소화\n- Redis 접근은 내부망 전용 + TLS',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '분산 락(Distributed Lock)을 Redis로 구현할 때 주의해야 할 점은?', '분산 락(Distributed Lock)을 레디스로 구현할 때 주의해야 할 점은?', '캐싱',
 '**분산 락의 필요성:**\n여러 서버 인스턴스가 동일 자원(재고, 쿠폰 발급)에 동시 접근할 때 레이스 컨디션 방지.\n\n**잘못된 구현 (NOT 사용):**\n```java\n// 원자적이지 않음 → 레이스 컨디션 발생\nif (!redis.exists(lockKey)) {   // 체크\n    redis.set(lockKey, "locked"); // 세트 (두 서버가 동시에 체크 통과 가능)\n}\n```\n\n**올바른 구현 — SET NX EX (원자적):**\n```java\n// SETNX + EX 원자적으로 실행\nBoolean acquired = redis.set(\n    lockKey,\n    lockValue,       // 고유값 (UUID) — 내가 건 락인지 확인용\n    SetArgs.Builder.nx().ex(30) // 30초 만료\n);\n\nif (Boolean.TRUE.equals(acquired)) {\n    try {\n        // 임계 영역 실행\n        processOrder();\n    } finally {\n        // 내가 건 락만 해제 (Lua 스크립트로 원자적 확인+삭제)\n        releaseLock(lockKey, lockValue);\n    }\n}\n```\n\n**락 해제 (Lua 스크립트 필수):**\n```lua\n-- 원자적 확인 + 삭제\nif redis.call("get", KEYS[1]) == ARGV[1] then\n    return redis.call("del", KEYS[1])\nelse\n    return 0\nend\n```\n이유: 확인과 삭제 사이에 다른 서버가 같은 키를 재획득할 수 있음\n\n**Redlock 알고리즘 (고가용성):**\n```\n단일 Redis 장애 시 락 소실 위험\n→ 5개의 독립 Redis 노드에 락 획득 시도\n→ 과반수(3개 이상) 획득 시 유효한 락으로 인정\n```\n\n**주의사항:**\n1. 만료 시간은 임계 영역 처리 시간보다 충분히 길게\n2. 처리 중 만료되면 다른 서버가 동시 진입 가능 → 워치독(Watchdog) 갱신\n3. Redisson 라이브러리: 워치독, Redlock, Fair Lock 등 제공\n\n```java\n// Redisson 권장\nRLock lock = redisson.getLock("order:lock:" + orderId);\nlock.lock(30, TimeUnit.SECONDS); // 워치독 자동 갱신\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '캐시 독(Cache Poisoning) 공격과 방어 방법을 설명해주세요.', '캐시 독(Cache Poisoning) 공격과 방어 방법을 설명해주세요.', '캐싱',
 '**Cache Poisoning (캐시 오염):**\n공격자가 캐시에 잘못된/악의적인 데이터를 저장시켜 다른 사용자에게 잘못된 응답을 제공하게 만드는 공격.\n\n**공격 유형:**\n\n**1. Web Cache Poisoning (HTTP 헤더 조작):**\n```\n공격자: GET /home\nHost: example.com\nX-Forwarded-Host: attacker.com\n\n→ 서버가 X-Forwarded-Host를 신뢰하여 응답에 포함\n→ CDN이 attacker.com 참조 응답을 캐시\n→ 일반 사용자도 같은 응답 받음 → XSS/리다이렉션 가능\n```\n\n**2. Response Splitting:**\n```\nHTTP 헤더에 CR/LF 주입으로 가짜 응답 삽입\n```\n\n**3. DNS Cache Poisoning:**\n```\nDNS 서버의 캐시에 위조된 IP 주소 주입\n→ 사용자가 정상 도메인 접속 시 악의적 서버로 연결\n```\n\n**방어 방법:**\n\n**1. 입력 검증 강화:**\n```java\n// 화이트리스트 기반 헤더 검증\nString host = request.getHeader("Host");\nif (!ALLOWED_HOSTS.contains(host)) {\n    throw new BadRequestException("Invalid host");\n}\n// X-Forwarded-For, X-Forwarded-Host 등 신뢰 설정 명확히\n```\n\n**2. Vary 헤더 올바른 사용:**\n```\nVary: Accept-Encoding, Accept-Language\n→ 다른 헤더 조합은 다른 캐시 항목으로 분리\n→ 공격자 헤더가 캐시 키에 포함되지 않도록\n```\n\n**3. Cache Key 엄격 설계:**\n```\n캐시 키 = URL + 화이트리스트 헤더만 포함\n임의 헤더는 캐시 키에서 제외\n```\n\n**4. Content Security Policy (CSP):**\n```\nContent-Security-Policy: default-src ''self''\n→ 오염된 캐시가 외부 스크립트 로드 시도해도 차단\n```\n\n**5. DNSSEC:**\nDNS 응답에 디지털 서명 → DNS Cache Poisoning 방어',
 'MODEL_ANSWER', TRUE, NOW());

-- ============================================================
-- 메시지큐 (6문항)
-- ============================================================

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '대용량 이벤트 스트리밍 시스템을 설계할 때 Kafka 클러스터를 어떻게 구성하나요?', '대용량 이벤트 스트리밍 시스템을 설계할 때 카프카 클러스터를 어떻게 구성하나요?', '메시지큐',
 '**Kafka 클러스터 구성 요소:**\n```\n[Producer 서비스들]\n    ↓\n[Kafka Cluster]\n├── Broker 1 (Leader: P0, P3)\n├── Broker 2 (Leader: P1, P4, Follower: P0)\n└── Broker 3 (Leader: P2, Follower: P1, P3)\n    ↓\n[Consumer Group들]\n```\n\n**프로덕션 최소 구성:**\n```\nBroker: 3개 이상 (과반수 합의)\nZookeeper → KRaft 모드 (Kafka 3.x, ZK 제거)\nReplication Factor: 3 (브로커 1대 장애 허용)\nmin.insync.replicas: 2 (최소 2개 복제본 동기화 후 응답)\n```\n\n**파티션 수 결정:**\n```\n파티션 수 = max(목표 TPS / 파티션당 TPS, Consumer 수)\n\n예: 목표 100만 TPS, 파티션당 10만 TPS → 최소 10개 파티션\n일반적으로 처음에 넉넉히 설정 (나중에 늘리기 어려움)\n```\n\n**Producer 설정 (안정성):**\n```properties\nacks=all                    # 모든 ISR에 복제 후 응답\nenable.idempotence=true     # 중복 전송 방지\nretries=Integer.MAX_VALUE   # 재시도 무한\nmax.in.flight.requests.per.connection=5\n```\n\n**Consumer 설정:**\n```properties\nenable.auto.commit=false    # 수동 커밋\nmax.poll.interval.ms=300000 # 처리 시간 초과 시 리밸런싱\nmax.poll.records=500        # 배치 크기\n```\n\n**모니터링 핵심 지표:**\n- Under-Replicated Partitions (0이어야 정상)\n- Consumer Group Lag\n- Broker Disk 사용률\n- Network I/O\n\n**Kafka Connect:**\n```\nDB → [Debezium Source Connector] → Kafka → [Sink Connector] → Elasticsearch\n// 코드 없이 데이터 파이프라인 구성\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', 'Dead Letter Queue(DLQ) 운영 전략과 실패 메시지 재처리 아키텍처를 설계해주세요.', 'Dead Letter Queue(DLQ) 운영 전략과 실패 메시지 재처리 아키텍처를 설계해주세요.', '메시지큐',
 '**DLQ 아키텍처:**\n```\n[메인 토픽]\n    ↓ Consumer 처리 실패\n[재시도 토픽들 — 지수 백오프]\n├── retry-topic-1s   (1초 후 재시도)\n├── retry-topic-30s  (30초 후 재시도)\n├── retry-topic-5m   (5분 후 재시도)\n└── retry-topic-1h   (1시간 후 재시도)\n    ↓ 모든 재시도 실패\n[DLQ (Dead Letter Queue)]\n    ↓\n[DLQ 모니터링 + 알림]\n    ↓ 운영자 분석 후\n[수동/자동 재처리 또는 폐기]\n```\n\n**Spring Kafka 재시도 설정:**\n```java\n@Bean\npublic DefaultErrorHandler errorHandler() {\n    // 지수 백오프: 1초, 2초, 4초, 8초\n    ExponentialBackOffWithMaxRetries backOff = \n        new ExponentialBackOffWithMaxRetries(4);\n    backOff.setInitialInterval(1000L);\n    backOff.setMultiplier(2.0);\n\n    DefaultErrorHandler handler = new DefaultErrorHandler(\n        new DeadLetterPublishingRecoverer(kafkaTemplate),\n        backOff\n    );\n    // 재시도 불필요한 예외 (비즈니스 로직 오류)\n    handler.addNotRetryableExceptions(\n        ValidationException.class,\n        DataIntegrityViolationException.class\n    );\n    return handler;\n}\n```\n\n**DLQ 메시지 구조 (헤더 보존):**\n```\nDLQ 메시지 헤더:\n- kafka_dlt-original-topic: orders\n- kafka_dlt-original-partition: 2\n- kafka_dlt-original-offset: 1234\n- kafka_dlt-exception-message: NullPointerException...\n- kafka_dlt-exception-fqcn: java.lang.NullPointerException\n```\n\n**운영 전략:**\n1. DLQ 메시지 수 알림 (Slack, PagerDuty)\n2. 오류 유형별 분류 (일시적 vs 영구적)\n3. 일시적 오류: 자동 재처리 도구\n4. 영구적 오류 (데이터 이상): 수동 수정 후 재처리\n5. DLQ 보관 기간: 최소 7일\n\n**재처리 API:**\n```java\n@PostMapping("/admin/dlq/replay")\npublic void replayDLQ(@RequestBody ReplayRequest req) {\n    // DLQ 메시지를 원본 토픽으로 재발행\n    kafkaTemplate.send(req.getOriginalTopic(), message);\n}\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '이벤트 기반 아키텍처(Event-Driven Architecture)에서 이벤트 스키마 진화(Schema Evolution)를 어떻게 관리하나요?', '이벤트 기반 아키텍처(Event-Driven Architecture)에서 이벤트 스키마 진화(Schema Evolution)를 어떻게 관리하나요?', '메시지큐',
 '**문제:**\n이벤트 스키마 변경 시 Producer와 Consumer가 서로 다른 스키마로 이벤트를 처리하면 역직렬화 오류 발생.\n\n**Schema Registry 활용 (Confluent Schema Registry):**\n```\n[Producer]\n→ 스키마를 Schema Registry에 등록/확인\n→ schema_id + 직렬화된 데이터 전송\n\n[Kafka Topic]: [magic_byte][schema_id (4byte)][avro/json 데이터]\n\n[Consumer]\n→ schema_id로 Schema Registry에서 스키마 조회\n→ 역직렬화\n```\n\n**Apache Avro 스키마 진화 규칙:**\n```json\n// v1 스키마\n{\n  "type": "record",\n  "name": "OrderEvent",\n  "fields": [\n    {"name": "orderId", "type": "long"},\n    {"name": "userId", "type": "long"},\n    {"name": "amount", "type": "double"}\n  ]\n}\n\n// v2 스키마 (하위 호환 변경)\n{\n  "fields": [\n    {"name": "orderId", "type": "long"},\n    {"name": "userId", "type": "long"},\n    {"name": "amount", "type": "double"},\n    {"name": "currency", "type": "string", "default": "KRW"} // 기본값 필수\n  ]\n}\n```\n\n**호환성 모드:**\n```\nBACKWARD: 새 Consumer가 구 Producer 메시지 처리 가능 (필드 추가)\nFORWARD: 구 Consumer가 새 Producer 메시지 처리 가능 (필드 삭제)\nFULL: 양방향 호환\n```\n\n**필드 삭제 전략:**\n```\n1단계: Deprecated 마킹 (Consumer들이 해당 필드 사용 중단)\n2단계: 모든 Consumer 배포 완료 확인\n3단계: Producer에서 필드 제거\n4단계: 스키마에서 삭제\n```\n\n**이벤트 버전 관리:**\n```java\npublic class OrderEvent {\n    private int eventVersion = 2; // 명시적 버전\n    private String eventType = "OrderCreated";\n    // Consumer가 버전 기반 분기 처리 가능\n}\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '실시간 스트림 처리(Stream Processing)와 배치 처리(Batch Processing)의 차이와 Lambda/Kappa 아키텍처를 설명해주세요.', '실시간 스트림 처리(Stream Processing)와 배치 처리(Batch Processing)의 차이와 람다/Kappa 아키텍처를 설명해주세요.', '메시지큐',
 '**배치 처리:**\n일정 주기(시간, 일)로 누적된 데이터를 한꺼번에 처리.\n```\n매일 새벽 2시: 전일 주문 데이터 집계 → 정산 보고서 생성\n특징: 높은 처리량, 높은 레이턴시 (최대 24시간)\n도구: Apache Spark, Hadoop MapReduce\n```\n\n**스트림 처리:**\n데이터가 생성되는 즉시 처리.\n```\n주문 이벤트 발생 → 즉시 재고 업데이트, 추천 점수 갱신\n특징: 낮은 레이턴시 (초~분), 실시간 인사이트\n도구: Kafka Streams, Apache Flink, Apache Spark Streaming\n```\n\n**Lambda 아키텍처:**\n배치 레이어 + 스피드 레이어를 함께 운영.\n```\n[데이터 소스]\n    ├── [배치 레이어] → Spark → 정확한 집계 (수시간~일 지연)\n    └── [스피드 레이어] → Flink → 근사 실시간 결과\n                                    ↓\n                          [서빙 레이어] → 두 결과 병합 → 쿼리 제공\n```\n단점: 두 시스템 동시 관리 복잡도, 코드 중복\n\n**Kappa 아키텍처:**\nKafka를 중심으로 스트림 처리만으로 단순화.\n```\n[Kafka (이벤트 영구 보관)]\n    ↓ 실시간 스트림 처리\n[Kafka Streams / Flink]\n    ↓\n[서빙 레이어]\n\n재처리 필요 시: Kafka 처음부터 재소비\n```\n\n**Kafka Streams 예시 (실시간 집계):**\n```java\nKStream<String, OrderEvent> orders = builder.stream("orders");\nKTable<String, Long> orderCountPerUser = orders\n    .groupBy((key, value) -> value.getUserId())\n    .count(Materialized.as("order-counts"));\n\norderCountPerUser.toStream().to("user-order-counts");\n```\n\n**선택 기준:**\n- 정확한 집계, 대용량 히스토리 분석 → 배치\n- 실시간 대시보드, 알림, 이상 탐지 → 스트림\n- 둘 다 필요 → Kappa (단순) 또는 Lambda (검증된 정확도 필요)',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '메시지 큐 기반 시스템에서 백프레셔(Backpressure)를 어떻게 처리하나요?', '메시지 큐 기반 시스템에서 백프레셔(Backpressure)를 어떻게 처리하나요?', '메시지큐',
 '**백프레셔 (Backpressure):**\nConsumer의 처리 속도 < Producer의 생산 속도일 때, 큐에 메시지가 무한히 쌓이는 현상.\n\n**백프레셔 미처리 시 문제:**\n```\n큐 크기 무한 증가 → 메모리 고갈 → OOM 또는 시스템 전체 장애\n또는 Consumer가 처리 불가한 양을 받아 더 느려지는 악순환\n```\n\n**Kafka에서의 백프레셔 처리:**\n\n**1. Consumer 처리량 조절:**\n```properties\nmax.poll.records=100        # 한 번에 처리할 최대 메시지 수\nmax.poll.interval.ms=300000 # 처리 타임아웃\nfetch.min.bytes=1024        # 최소 배치 크기\n```\n\n**2. 동적 Consumer 확장 (Auto Scaling):**\n```\nKafka Consumer Lag 모니터링\n→ Lag 임계치(10000) 초과 시 Auto Scaling 트리거\n→ Consumer Pod 증가 (파티션 수 이내)\n```\n\n**3. 처리 스로틀링:**\n```java\n@KafkaListener(topics = "orders")\npublic void consume(List<OrderEvent> events) {\n    // 배치 처리로 DB 부하 감소\n    orderService.bulkProcess(events);\n\n    // 외부 API 호출 시 레이트 리미팅\n    rateLimiter.acquire(events.size());\n}\n```\n\n**4. 서킷 브레이커 + 백프레셔 연계:**\n```\nConsumer 의존 서비스(DB, API) 장애 감지\n→ Circuit Open → Consumer 일시 중단\n→ 큐에 메시지 보존 (Kafka 특성)\n→ 서비스 복구 → Consumer 재개\n```\n\n**Reactive Streams 백프레셔 (Project Reactor):**\n```java\nKafkaReceiver.create(receiverOptions)\n    .receive()\n    .publishOn(Schedulers.boundedElastic())\n    .flatMap(record -> processRecord(record), 10) // 동시 처리 최대 10개\n    .subscribe();\n```\n\n**모니터링 지표:**\n- Consumer Lag 추이\n- Consumer 처리 시간 (P99)\n- DLQ 유입 속도\n- 메모리 사용률',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '글로벌 이벤트 스트리밍 시스템에서 멀티 리전 Kafka 클러스터를 어떻게 구성하나요?', '글로벌 이벤트 스트리밍 시스템에서 멀티 리전 카프카 클러스터를 어떻게 구성하나요?', '메시지큐',
 '**단일 리전의 한계:**\n- 리전 장애 시 전체 이벤트 파이프라인 중단\n- 글로벌 사용자에게 높은 레이턴시\n- 규정 준수 (데이터 주권, GDPR — 데이터가 특정 리전 밖으로 나가면 안 됨)\n\n**멀티 리전 Kafka 패턴:**\n\n**1. Active-Passive (MirrorMaker2):**\n```\n[서울 Kafka (Primary)] ──MirrorMaker2──→ [버지니아 Kafka (DR)]\n\n평상시: 서울만 사용\n장애 시: DNS/로드밸런서를 버지니아로 전환\n```\n\n**Kafka MirrorMaker2 설정:**\n```properties\nclusters = seoul, virginia\nseoul.bootstrap.servers = seoul-kafka:9092\nvirginia.bootstrap.servers = virginia-kafka:9092\nseoul->virginia.enabled = true\nseoul->virginia.topics = orders,payments\n# 복제된 토픽: virginia.orders, virginia.payments\n```\n\n**2. Active-Active:**\n```\n[서울 Kafka] ←── MirrorMaker2 ──→ [버지니아 Kafka]\n\n한국 사용자 → 서울 Kafka\n미국 사용자 → 버지니아 Kafka\n양방향 복제 → 각 리전 데이터 동기화\n```\n\n**순환 복제 방지:**\n```\nMirrorMaker2는 .source 접두사로 출처 추적\nseoul.orders → virginia 복제 시 virginia.seoul.orders로 저장\n→ 무한 루프 방지\n```\n\n**3. Confluent Cluster Linking:**\n```\nMirrorMaker2보다 낮은 레이턴시\n정확히 한 번 복제 보장\nCluster 간 직접 Consumer 오프셋 동기화\n```\n\n**데이터 주권 처리:**\n```\nGDPR 대상 데이터: EU 리전 토픽에만 저장\n글로벌 집계: 개인식별정보 제거 후 글로벌 토픽 복제\n```\n\n**RPO/RTO 목표:**\n- RPO (복구 시점 목표): < 1분 (MirrorMaker2 복제 지연)\n- RTO (복구 시간 목표): < 5분 (DNS 전환 + Consumer 재시작)',
 'MODEL_ANSWER', TRUE, NOW());

-- ============================================================
-- 마이크로서비스 (6문항)
-- ============================================================

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '팀 토폴로지(Team Topology)와 마이크로서비스 경계를 어떻게 정렬하나요?', '팀 토폴로지(Team Topology)와 마이크로서비스 경계를 어떻게 정렬하나요?', '마이크로서비스',
 '**Conway''s Law:**\n"조직이 설계하는 시스템은 그 조직의 커뮤니케이션 구조를 그대로 반영한다."\n→ 마이크로서비스 경계는 팀 구조와 정렬되어야 합니다.\n\n**Team Topology 4가지 팀 유형:**\n\n**1. Stream-Aligned Team (스트림 정렬 팀):**\n```\n비즈니스 도메인에 대한 E2E 책임\n예: 주문 팀 → 주문 서비스 전체 (BE + FE + DB)\n→ 해당 도메인 마이크로서비스 소유\n```\n\n**2. Platform Team (플랫폼 팀):**\n```\n다른 팀이 쉽게 개발/배포할 수 있는 기반 제공\n예: Kubernetes 클러스터, CI/CD 파이프라인, 모니터링\n→ 공통 인프라 서비스\n```\n\n**3. Enabling Team (지원 팀):**\n```\n특정 기술/역량을 다른 팀에 전파\n예: 보안 팀, DDD 전문가 팀\n→ 일시적 지원, 독립 서비스 없음\n```\n\n**4. Complicated Subsystem Team (복잡 서브시스템 팀):**\n```\n고도로 전문화된 기술이 필요한 서비스\n예: 추천 알고리즘 팀, 실시간 분석 팀\n→ 특수 목적 서비스\n```\n\n**DDD Bounded Context와의 정렬:**\n```\n[주문 도메인 (Bounded Context)]\n    ↕ 정렬\n[주문 팀 (Stream-Aligned)]\n    ↕ 소유\n[주문 서비스 + 주문 DB]\n```\n\n**팀 간 인터랙션 모드:**\n- Collaboration: 긴밀 협업 (임시, 신규 서비스 설계)\n- X-as-a-Service: API로 사용 (플랫폼 팀 제공)\n- Facilitating: 지식 전파 (지원 팀)\n\n**역 Conway 조작 (Reverse Conway Maneuver):**\n원하는 아키텍처에 맞게 팀을 먼저 재구성 → 자연스럽게 원하는 시스템 구조 나타남',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '마이크로서비스에서 데이터 일관성을 유지하는 패턴들을 비교하고 상황별 선택 기준을 제시해주세요.', '마이크로서비스에서 데이터 일관성을 유지하는 패턴들을 비교하고 상황별 선택 기준을 제시해주세요.', '마이크로서비스',
 '**마이크로서비스 데이터 일관성의 어려움:**\n각 서비스가 독립 DB를 가지므로 ACID 트랜잭션 불가. 분산 환경에서 일관성 유지 패턴이 필요합니다.\n\n**패턴 1: Two-Phase Commit (2PC)**\n```\n[Coordinator]\n1단계(Prepare): 모든 서비스에 트랜잭션 준비 요청\n    → 서비스들: "준비 완료" 응답\n2단계(Commit): 모든 준비 확인 후 커밋 명령\n    → 서비스들: 실제 커밋\n```\n장점: 강한 일관성\n단점: Coordinator SPOF, 느림, 마이크로서비스에서 잘 사용 안 함\n\n**패턴 2: Saga 패턴**\n```\n각 서비스가 로컬 트랜잭션 + 보상 트랜잭션\n실패 시 역순으로 보상 실행 (롤백 유사)\n→ 결과적 일관성\n```\n\n**패턴 3: Outbox + CDC**\n```\nDB 트랜잭션과 이벤트 발행의 원자성 보장\n→ 비즈니스 로직 + 이벤트를 같은 트랜잭션으로\n```\n\n**패턴 4: CQRS + Event Sourcing**\n```\n모든 상태 변경을 이벤트로 → 다양한 Read Model 생성\n→ 읽기 일관성은 Eventual\n```\n\n**상황별 선택:**\n| 상황 | 패턴 | 이유 |\n|------|------|------|\n| 결제 + 재고 원자적 처리 | Saga (Orchestration) | 보상 트랜잭션 명확 |\n| 이벤트 유실 방지 | Outbox + CDC | DB 트랜잭션 보장 |\n| 복잡한 읽기 쿼리 | CQRS | 읽기 모델 최적화 |\n| 완전한 감사 로그 | Event Sourcing | 모든 변경 이력 보존 |\n\n**보상 트랜잭션 설계 원칙:**\n- 모든 비즈니스 트랜잭션에 보상 정의 필수\n- 보상도 실패 가능 → 재시도 + 수동 개입 절차\n- 멱등성 보장 필수',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', 'Kubernetes 환경에서 마이크로서비스 운영 시 핵심 설계 패턴을 설명해주세요.', '쿠버네티스 환경에서 마이크로서비스 운영 시 핵심 설계 패턴을 설명해주세요.', '마이크로서비스',
 '**Kubernetes 기반 마이크로서비스 핵심 패턴:**\n\n**1. 헬스 체크 정밀 설계:**\n```yaml\nlivenessProbe:      # 재시작 여부 결정\n  httpGet:\n    path: /actuator/health/liveness\n    port: 8080\n  initialDelaySeconds: 30\n  periodSeconds: 10\n\nreadinessProbe:     # 트래픽 수신 가능 여부\n  httpGet:\n    path: /actuator/health/readiness  # DB, Redis 연결 포함\n    port: 8080\n  initialDelaySeconds: 20\n  periodSeconds: 5\n\nstartupProbe:       # 느린 시작 허용 (JVM 워밍업)\n  httpGet:\n    path: /actuator/health\n    port: 8080\n  failureThreshold: 30\n  periodSeconds: 10\n```\n\n**2. 그레이스풀 셧다운:**\n```yaml\nspec:\n  terminationGracePeriodSeconds: 60\n  containers:\n  - lifecycle:\n      preStop:\n        exec:\n          command: ["sh", "-c", "sleep 5"]  # 로드밸런서 제거 대기\n```\n\n**3. 리소스 제한 (Resource Limits):**\n```yaml\nresources:\n  requests:    # 스케줄링 기준\n    memory: "256Mi"\n    cpu: "250m"\n  limits:      # 최대 사용량\n    memory: "512Mi"\n    cpu: "500m"\n# requests != limits → Burstable QoS\n# JVM 서비스: limits.memory = Xmx + 헤드룸 (20%)\n```\n\n**4. Pod Disruption Budget (PDB):**\n```yaml\napiVersion: policy/v1\nkind: PodDisruptionBudget\nspec:\n  minAvailable: 2  # 업그레이드 중 최소 2개 유지\n  selector:\n    matchLabels:\n      app: order-service\n```\n\n**5. 수평 Pod 자동 확장 (HPA):**\n```yaml\nspec:\n  metrics:\n  - type: External\n    external:\n      metric:\n        name: kafka_consumer_lag\n      target:\n        type: AverageValue\n        averageValue: "1000"  # 파티션당 Lag 1000 초과 시 확장\n```\n\n**6. 시크릿 관리:**\n```\n환경변수 직접 주입 금지\n→ Kubernetes Secret + Vault Agent Sidecar\n→ 또는 AWS Secrets Manager + External Secrets Operator\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '마이크로서비스 보안 아키텍처에서 Zero Trust 모델을 어떻게 구현하나요?', '마이크로서비스 보안 아키텍처에서 Zero Trust 모델을 어떻게 구현하나요?', '마이크로서비스',
 '**Zero Trust 원칙:**\n"아무것도 신뢰하지 않는다 — 내부 네트워크라도 검증 후 접근"\n기존 경계 보안(방화벽 안 = 신뢰)의 한계 극복.\n\n**Zero Trust 핵심 원칙:**\n1. 항상 검증 (Verify Explicitly)\n2. 최소 권한 접근 (Least Privilege Access)\n3. 침해 가정 (Assume Breach)\n\n**구현 요소:**\n\n**1. 서비스 간 mTLS (상호 TLS):**\n```\n기존: 서비스A → 서비스B (인증 없음, IP만 확인)\nZero Trust: 서비스A ←→ 서비스B (양방향 인증서 검증)\n\n구현:\n- Istio Service Mesh: 자동 mTLS 적용\n- SPIFFE/SPIRE: 서비스 ID 인증서 자동 발급/갱신\n```\n\n**2. 워크로드 ID (Workload Identity):**\n```\nKubernetes Service Account → OIDC 토큰 발급\n→ AWS IAM Role for Service Account (IRSA)\n→ 각 서비스가 필요한 AWS 리소스만 접근 가능\n\nexample:\norder-service Service Account\n→ IAM Role: order-service-role\n→ S3 특정 버킷 Read Only 권한만\n```\n\n**3. 네트워크 정책 (Network Policy):**\n```yaml\napiVersion: networking.k8s.io/v1\nkind: NetworkPolicy\nspec:\n  podSelector:\n    matchLabels:\n      app: payment-service\n  ingress:\n  - from:\n    - podSelector:\n        matchLabels:\n          app: order-service  # order-service에서만 수신\n  egress:\n  - to:\n    - podSelector:\n        matchLabels:\n          app: payment-db  # payment-db로만 송신\n```\n\n**4. 동적 시크릿 (Dynamic Secrets):**\n```\nHashiCorp Vault:\n→ DB 접근 자격증명을 짧은 TTL(1시간)로 동적 발급\n→ 시크릿 노출 시 자동 만료 → 피해 최소화\n```\n\n**5. API 접근 감사:**\n```\n모든 API 호출 로깅: 누가, 언제, 어떤 리소스에\n이상 행동 탐지: 비정상적 접근 패턴 알림\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '마이크로서비스의 테스트 전략과 테스트 피라미드를 어떻게 설계하나요?', '마이크로서비스의 테스트 전략과 테스트 피라미드를 어떻게 설계하나요?', '마이크로서비스',
 '**마이크로서비스 테스트 피라미드:**\n```\n        [E2E 테스트]         ← 소수, 느림, 고비용\n      [통합 테스트]           ← 중간\n    [컨트랙트 테스트]          ← 서비스 간 계약 검증\n  [컴포넌트 테스트]            ← 서비스 단위 격리\n[단위 테스트]                  ← 다수, 빠름, 저비용\n```\n\n**1. 단위 테스트 (Unit Test):**\n```java\n// 순수 비즈니스 로직, 외부 의존성 Mock\n@ExtendWith(MockitoExtension.class)\nclass OrderServiceTest {\n    @Mock OrderRepository orderRepository;\n    @InjectMocks OrderService orderService;\n\n    @Test\n    void 재고_부족_시_주문_실패() {\n        when(inventoryClient.getStock(1L)).thenReturn(0);\n        assertThrows(InsufficientStockException.class,\n            () -> orderService.createOrder(request));\n    }\n}\n```\n\n**2. 컨트랙트 테스트 (Contract Test — Pact):**\n```java\n// Consumer가 기대하는 응답을 계약으로 정의\n// Provider 변경 시 계약 위반 자동 감지\n@PactTestFor(providerName = "order-service")\nclass OrderConsumerContractTest {\n    @Pact(consumer = "payment-service")\n    public RequestResponsePact createPact(PactDslWithProvider builder) {\n        return builder\n            .uponReceiving("주문 조회")\n            .path("/orders/1")\n            .method("GET")\n            .willRespondWith()\n            .status(200)\n            .body(new PactDslJsonBody()\n                .numberValue("id", 1)\n                .stringValue("status", "CONFIRMED"))\n            .toPact();\n    }\n}\n```\n\n**3. 컴포넌트 테스트 (서비스 격리):**\n```java\n// 실제 Spring Context, 외부 서비스는 WireMock으로 대체\n@SpringBootTest\n@AutoConfigureWireMock\nclass OrderComponentTest {\n    // Kafka, 외부 API → WireMock\n    // DB → Testcontainers (실제 MySQL)\n}\n```\n\n**4. Testcontainers 활용:**\n```java\n@Testcontainers\nclass OrderRepositoryTest {\n    @Container\n    static MySQLContainer<?> mysql = new MySQLContainer<>("mysql:8.0");\n    @Container\n    static GenericContainer<?> redis = new GenericContainer<>("redis:7");\n}\n```\n\n**5. E2E 테스트 범위 최소화:**\n- 핵심 사용자 여정 5~10개만 (로그인 → 주문 → 결제)\n- 야간 배치로 실행 (속도 < 신뢰성)',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '대규모 마이크로서비스 환경에서 카오스 엔지니어링(Chaos Engineering)을 어떻게 도입하나요?', '대규모 마이크로서비스 환경에서 카오스 엔지니어링(Chaos Engineering)을 어떻게 도입하나요?', '마이크로서비스',
 '**카오스 엔지니어링 정의:**\n"프로덕션 환경에서 의도적으로 장애를 주입하여 시스템의 회복 탄력성을 사전에 검증하는 방법론"\n— Netflix의 Chaos Monkey에서 시작\n\n**도입 원칙 (GameDay):**\n```\n1. 정상 상태 정의 (Steady State)\n   예: 에러율 < 0.1%, P99 레이턴시 < 200ms\n\n2. 가설 수립\n   "결제 서비스 장애 시 주문 서비스는 서킷 브레이커로 빠른 실패하고\n   주문은 보류 상태로 저장되어야 한다"\n\n3. 통제된 장애 주입\n4. 결과 관찰 및 검증\n5. 취약점 발견 시 개선\n```\n\n**장애 주입 유형:**\n```\n인프라 레벨:\n- Pod/Node 종료 (Chaos Monkey)\n- 네트워크 레이턴시 추가 (tc netem)\n- 네트워크 패킷 손실\n- 디스크 I/O 고갈\n\n애플리케이션 레벨:\n- 특정 API 응답 지연\n- 에러 응답 반환\n- 메모리 고갈 (Memory Hog)\n- CPU 고갈\n\n데이터 레벨:\n- DB Failover\n- 캐시 플러시\n```\n\n**Chaos Mesh (Kubernetes):**\n```yaml\napiVersion: chaos-mesh.org/v1alpha1\nkind: NetworkChaos\nspec:\n  action: delay\n  duration: "30s"\n  selector:\n    namespaces: ["production"]\n    labelSelectors:\n      app: payment-service\n  delay:\n    latency: "100ms"\n    jitter: "50ms"\n```\n\n**AWS Fault Injection Simulator (FIS):**\n```\nEC2 종료, RDS Failover, ECS 태스크 종료 등\nAWS 네이티브 카오스 실험\n```\n\n**안전 장치:**\n- Abort 조건 정의 (에러율 > 5% 시 자동 중단)\n- 비즈니스 시간 외 실행\n- 점진적 폭발 반경 확대 (dev → staging → prod)\n- 관련 팀 사전 공지\n\n**성숙도 모델:**\n1. Dev 환경 카오스\n2. Staging 환경 게임데이\n3. 프로덕션 소규모 카오스\n4. 프로덕션 지속적 카오스 (Netflix 수준)',
 'MODEL_ANSWER', TRUE, NOW());

-- ============================================================
-- 로드밸런싱 (6문항)
-- ============================================================

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', 'URL Shortener 시스템을 설계해주세요. (트래픽: 초당 쓰기 1000건, 읽기 100,000건)', '유알엘 Shortener 시스템을 설계해주세요. (트래픽: 초당 쓰기 1000건, 읽기 100,000건)', '로드밸런싱',
 '**요구사항 분석:**\n- 쓰기: 1000 RPS (단축 URL 생성)\n- 읽기: 100,000 RPS (리다이렉션) → 읽기 집중 시스템\n- URL 저장: 10년, 하루 1000건 × 365 × 10 = 약 36억 URL\n\n**고수준 아키텍처:**\n```\n[클라이언트]\n    ↓\n[CDN] — 인기 URL 리다이렉션 캐싱\n    ↓\n[API Gateway + Rate Limiter]\n    ↓\n[로드밸런서]\n    ├── [쓰기 서비스] → [DB Primary]\n    └── [읽기 서비스] → [Redis Cache] → [DB Read Replica]\n```\n\n**단축 키 생성 전략:**\n```\n방법 1: MD5(URL) 앞 6~8자리\n→ 충돌 가능성, 중복 체크 필요\n\n방법 2: Base62 인코딩 (a-zA-Z0-9)\n62^7 ≈ 3.5조 가지 → 36억 URL 충분\n\n방법 3: 분산 ID 생성기 (Snowflake)\n→ 64비트 ID → Base62 인코딩 → 7~8자리\n→ 충돌 없음, 순서 보장\n```\n\n**DB 스키마:**\n```sql\nCREATE TABLE url_mappings (\n    short_key  CHAR(8) PRIMARY KEY,\n    long_url   TEXT NOT NULL,\n    user_id    BIGINT,\n    created_at DATETIME,\n    expires_at DATETIME,\n    click_count BIGINT DEFAULT 0\n) ENGINE=InnoDB;\n\nINDEX: short_key (PK), expires_at\n```\n\n**읽기 최적화 (100K RPS):**\n```\nCDN: 인기 URL 캐싱 → Redis 호출 차단\nRedis: TTL 24시간, short_key → long_url 매핑\n→ DB 부하 = 전체의 1~5% 수준\n```\n\n**쓰기 확장:**\n```\nSharded DB (short_key 기반)\nShort_key 첫 글자로 샤딩: a-f → Shard1, g-p → Shard2, q-z → Shard3\n```\n\n**만료 처리:**\n```\nTTL 기반 Redis 자동 만료\nDB에서는 Scheduled Job으로 배치 삭제 (새벽 시간)\n```\n\n**분석 데이터:**\n```\n클릭 이벤트 → Kafka → Flink → ClickHouse (OLAP)\n실시간 통계 제공 (국가별, 디바이스별 클릭수)\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '실시간 채팅 시스템을 설계해주세요. (DAU 1000만, 메시지 초당 10만건)', '실시간 채팅 시스템을 설계해주세요. (디에이유 1000만, 메시지 초당 10만건)', '로드밸런싱',
 '**요구사항:**\n- DAU 1000만, 동시 접속 100만\n- 초당 메시지 10만건\n- 실시간 전달 (< 100ms)\n- 오프라인 메시지 저장 및 재전달\n\n**아키텍처:**\n```\n[클라이언트 (WebSocket)]\n    ↓\n[WebSocket Gateway 서버들 — 상태 저장]\n    ↓ 메시지 라우팅\n[Kafka]\n    ↓\n[메시지 처리 서비스]\n    ├── [Redis] — 활성 세션, 프레즌스\n    ├── [Cassandra] — 메시지 영구 저장\n    └── [WebSocket Gateway] — 수신자 서버로 전달\n```\n\n**WebSocket 연결 관리:**\n```\nL4 로드밸런서 → Sticky Session으로 동일 서버에 연결 유지\n서버당 동시 연결: ~10만 (10 서버 × 10만 = 100만)\n\nRedis에 사용자-서버 매핑 저장:\nuser:session:userId → serverId (IP:PORT)\n```\n\n**메시지 전달 흐름:**\n```\n1. User A (서버1) → 메시지 전송\n2. 서버1 → Kafka 발행 (chat:roomId 토픽)\n3. Kafka → 메시지 처리 서비스\n4. 처리 서비스 → Cassandra에 저장\n5. 처리 서비스 → Redis에서 User B의 서버 조회\n6. User B의 서버2에 내부 API로 전달\n7. 서버2 → User B WebSocket으로 실시간 전달\n```\n\n**오프라인 메시지:**\n```\nUser B 오프라인 → Redis에 서버 매핑 없음\n→ Cassandra에 메시지 저장 (is_delivered = false)\n→ User B 재접속 → 미전달 메시지 일괄 전송\n→ Push Notification (FCM/APNs)\n```\n\n**메시지 저장 (Cassandra):**\n```\nPARTITION KEY: (room_id, bucket)  // bucket = YYYYMMDD\nCLUSTERING: message_id DESC       // 최신 메시지 먼저\n\n→ 채팅방 ID 기반 파티셔닝으로 균등 분산\n→ 시간 기반 버킷으로 파티션 크기 제어\n```\n\n**프레즌스 (온라인 상태):**\n```\nRedis: user:presence:userId → online/offline, TTL 60초\nWebSocket 연결 유지 시 30초마다 TTL 갱신\nTTL 만료 = 오프라인으로 판단\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '글로벌 CDN 아키텍처와 엣지 컴퓨팅(Edge Computing)을 어떻게 설계하나요?', '글로벌 씨디엔 아키텍처와 엣지 컴퓨팅(Edge Computing)을 어떻게 설계하나요?', '로드밸런싱',
 '**CDN 기본 구조:**\n```\n[오리진 서버 (한국 데이터센터)]\n    ↑ Cache Miss 시만 요청\n[CDN PoP (Point of Presence)]\n├── 서울 PoP\n├── 도쿄 PoP\n├── 싱가포르 PoP\n├── 프랑크푸르트 PoP\n└── 뉴욕 PoP\n    ↑ 가장 가까운 PoP\n[사용자]\n```\n\n**캐싱 전략:**\n```\n정적 자산 (CSS, JS, 이미지):\nCache-Control: public, max-age=31536000, immutable\n→ 1년 캐싱, 파일명에 해시 포함으로 캐시 무효화\n\nAPI 응답:\nCache-Control: public, max-age=60, stale-while-revalidate=300\n→ 60초 신선, 300초는 백그라운드 갱신 중 오래된 데이터 반환\n\n개인화 데이터:\nCache-Control: private, no-cache\n→ CDN 캐싱 금지\n```\n\n**엣지 컴퓨팅 (Edge Computing):**\n오리진 서버까지 가지 않고 CDN 엣지에서 로직 실행.\n\n```\nCloudflare Workers / AWS Lambda@Edge / Vercel Edge Functions\n```\n\n**엣지에서 처리 적합한 작업:**\n```javascript\n// Cloudflare Worker 예시\n// 1. A/B 테스트 — 엣지에서 분기\nexport default {\n  async fetch(request) {\n    const userId = getCookie(request, "userId");\n    const variant = hash(userId) % 2 === 0 ? "A" : "B";\n    const url = new URL(request.url);\n    url.pathname = `/variant-${variant}${url.pathname}`;\n    return fetch(url.toString());\n  }\n};\n\n// 2. 지역 기반 리다이렉션\n// 3. 인증 토큰 검증 (오리진 부하 감소)\n// 4. 요청/응답 변환\n// 5. Rate Limiting\n```\n\n**CDN 캐시 무효화:**\n```\n즉시 무효화 (Purge):\nPOST https://api.cloudflare.com/client/v4/zones/{zone}/purge_cache\n{ "files": ["https://example.com/products/1"] }\n\n태그 기반 무효화:\nCache-Tag: product-1\n→ product-1 태그 가진 모든 캐시 일괄 무효화\n```\n\n**Cache Miss 최소화:**\n```\nCache Fill Rate 모니터링\n인기 콘텐츠 프리워밍 (배포 직후)\n롱테일 콘텐츠는 CDN 캐싱 효율 낮음 → 오리진 최적화 집중\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '대규모 서비스의 데이터베이스 샤딩(Sharding) 전략을 설계하고 트레이드오프를 설명해주세요.', '대규모 서비스의 데이터베이스 샤딩(Sharding) 전략을 설계하고 트레이드오프를 설명해주세요.', '로드밸런싱',
 '**샤딩의 필요성:**\n단일 DB의 한계(수TB, 수백만 TPS)를 수평 분산으로 극복.\n\n**샤딩 방식:**\n\n**1. Range-based Sharding:**\n```\nuser_id 1~1000000  → Shard 1\nuser_id 1000001~2000000 → Shard 2\n\n장점: 범위 쿼리 효율적\n단점: 핫 샤드 (신규 가입자 집중), 불균등 분배\n```\n\n**2. Hash-based Sharding:**\n```\nshard = hash(user_id) % N\n\n장점: 균등 분배, 단순\n단점: 범위 쿼리 불가, 샤드 추가 시 대규모 재분배\n```\n\n**3. Consistent Hashing:**\n```\n해시 링에 샤드 배치\n새 샤드 추가 시 인접 샤드의 일부만 이동 (전체 재분배 X)\n\n장점: 샤드 추가/제거 영향 최소화\n단점: 구현 복잡도, 가상 노드로 불균등 완화 필요\n```\n\n**4. Directory-based Sharding:**\n```\n샤드 조회 테이블 별도 유지\nuser_id → shard_id 매핑\n\n장점: 가장 유연한 재샤딩\n단점: 조회 테이블이 SPOF, 추가 쿼리\n```\n\n**샤딩 키 선택 기준:**\n```\n1. 카디널리티 높을 것 (균등 분배)\n2. 핵심 쿼리 패턴과 정렬 (Cross-shard 쿼리 최소화)\n3. 변경되지 않을 값 (재샤딩 회피)\n\n좋음: user_id, order_id\n나쁨: status, category (카디널리티 낮음)\n```\n\n**Cross-shard 쿼리 처리:**\n```\n문제: SELECT * FROM orders WHERE user_id IN (1,2,3) \n      → 여러 샤드에 쿼리 병렬 실행 → 결과 합산\n\n해결:\n1. 애플리케이션 레벨 집산 (Scatter-Gather)\n2. Read 전용 비정규화 테이블 (모든 샤드 데이터 중앙 집계)\n3. CQRS — 읽기 모델은 단일 테이블 (Elasticsearch 등)\n```\n\n**재샤딩 전략:**\n```\n1. 더블 라이팅: 구 샤드 + 신 샤드 동시 쓰기\n2. 백그라운드 마이그레이션: 구 → 신 데이터 복사\n3. 트래픽 전환: 읽기부터 신 샤드로, 완료 후 구 샤드 제거\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '서비스 수준 목표(SLO)와 에러 버짓(Error Budget)을 기반으로 신뢰성을 관리하는 방법은?', '서비스 수준 목표(에스엘오)와 에러 버짓(Error Budget)을 기반으로 신뢰성을 관리하는 방법은?', '로드밸런싱',
 '**SRE 핵심 개념:**\n\n**SLI (Service Level Indicator):** 실제 측정되는 지표\n```\n- 가용성: 성공 응답수 / 전체 요청수\n- 레이턴시: P99 응답 시간 < 200ms 비율\n- 처리량: 초당 처리 요청 수\n- 에러율: 5xx 에러 비율\n```\n\n**SLO (Service Level Objective):** 목표 수준\n```\n가용성 SLO: 99.9% (월간 허용 다운타임: 43.8분)\n레이턴시 SLO: 95%의 요청이 200ms 이내\n```\n\n**Error Budget (에러 버짓):**\n```\n99.9% SLO → 에러 버짓 = 0.1% = 월 43.8분 다운타임 허용\n\n에러 버짓 소진율:\n- 느림 (< 50%): 더 빠른 배포 속도 가능\n- 보통 (50~100%): 현재 속도 유지\n- 소진 (100%): 신규 기능 배포 중단, 안정성에만 집중\n```\n\n**Error Budget 정책:**\n```\n[개발팀 관점]\n에러 버짓 여유 → 새 기능 배포, 실험 가능\n에러 버짓 소진 → 배포 동결, 신뢰성 작업만\n\n[비즈니스 관점]\n에러 버짓 = 혁신 속도와 안정성의 균형\n```\n\n**Prometheus + Grafana SLO 대시보드:**\n```yaml\n# SLO 설정 (sloth/pyrra)\nservice: payment-api\nslos:\n  - name: availability\n    description: "99.9% 가용성"\n    sli:\n      events:\n        error_query: sum(rate(http_requests_total{status=~"5.."}[5m]))\n        total_query: sum(rate(http_requests_total[5m]))\n    objective: 99.9\n```\n\n**다번율 소진 알림:**\n```\n번 레이트 = 1시간 소진율 × 720 (월 시간수)\n번 레이트 > 14 → 1시간 내 월 에러 버짓 7% 소진 → 즉시 대응\n번 레이트 > 1  → 정상 소진율 초과 → 주의\n```\n\n**SLO 설정 원칙:**\n- 100% SLO는 금물 (개선 여지 없음, 비용 급증)\n- 사용자가 실제 느끼는 만족도 기반 설정\n- 점진적 상향 (99% → 99.5% → 99.9%)',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '피드 시스템(타임라인)을 설계해주세요. (인스타그램/트위터 규모: DAU 1억)', '피드 시스템(타임라인)을 설계해주세요. (인스타그램/트위터 규모: 디에이유 1억)', '로드밸런싱',
 '**두 가지 접근법:**\n\n**Pull 모델 (Fetch on Read):**\n```\n피드 조회 시:\n1. 팔로잉 목록 조회 (최대 수천 명)\n2. 각 유저의 최신 포스트 조회\n3. 머지 & 정렬\n→ 쓰기 빠름, 읽기 느림 (O(N) 팔로잉 수)\n→ 셀럽(수백만 팔로워) 이슈 없음\n→ 단점: 조회 시 매우 느림\n```\n\n**Push 모델 (Fanout on Write):**\n```\n포스트 작성 시:\n1. 모든 팔로워의 피드 테이블에 즉시 삽입\n→ 쓰기 느림 (O(N) 팔로워 수)\n→ 읽기 빠름 (자신의 피드 테이블만 조회)\n→ 단점: 셀럽 1개 포스트 = 수백만 쓰기 폭발\n```\n\n**하이브리드 모델 (실제 서비스):**\n```\n일반 유저 (팔로워 < 10만): Push 모델\n셀럽 (팔로워 > 10만): Pull 모델\n\n피드 조회 시:\n→ 자신의 피드 캐시 (Push된 일반 유저 포스트)\n+ 팔로우 중인 셀럽 최신 포스트 (Pull, 병렬)\n→ 머지 → 정렬 → 반환\n```\n\n**데이터 저장:**\n```\n포스트: Cassandra (파티션: user_id, 클러스터링: post_id DESC)\n피드 캐시: Redis Sorted Set (score = timestamp)\n  ZADD feed:userId score postId\n  ZRANGE feed:userId 0 19 WITHSCORES  # 최신 20개\n\n미디어: S3 + CloudFront\n```\n\n**팔로워 목록:**\n```\nRedis Set: followers:userId → {follower1, follower2, ...}\nDB: 영구 저장 (MySQL 또는 Cassandra)\n```\n\n**피드 페이지네이션:**\n```\nCursor 기반:\nGET /feed?cursor=1234567890&limit=20\n→ timestamp < cursor 조건으로 다음 페이지\n→ 새 포스트 추가로 인한 중복/누락 없음\n```\n\n**성능 목표:**\n- 피드 조회 P99: < 100ms\n- 포스트 작성 후 팔로워 피드 반영: < 5초',
 'MODEL_ANSWER', TRUE, NOW());

-- ============================================================
-- API설계 (6문항)
-- ============================================================

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', 'API 게이트웨이 패턴과 BFF(Backend for Frontend) 패턴을 언제 선택하나요?', '에이피아이 게이트웨이 패턴과 비에프에프(Backend for Frontend) 패턴을 언제 선택하나요?', 'API설계',
 '**API Gateway 패턴:**\n모든 클라이언트(웹, 앱, IoT)가 동일한 단일 Gateway를 사용.\n\n```\n[웹 클라이언트]\n[iOS 앱]         →  [API Gateway]  →  [마이크로서비스들]\n[Android 앱]\n[IoT 기기]\n```\n\n**단점:**\n- 다양한 클라이언트 요구사항을 하나의 Gateway가 처리 → 복잡도 증가\n- 모바일 앱은 데이터 절약 중요, 웹은 풍부한 데이터 필요\n- Gateway 변경이 모든 클라이언트에 영향\n\n**BFF (Backend for Frontend) 패턴:**\n클라이언트 유형별로 전용 Backend를 운영.\n\n```\n[웹 클라이언트]    → [Web BFF]     → [마이크로서비스들]\n[iOS 앱]           → [Mobile BFF]  → [마이크로서비스들]\n[Android 앱]       → [Mobile BFF]\n[파트너 API]        → [Partner BFF] → [마이크로서비스들]\n```\n\n**BFF 장점:**\n- 각 클라이언트에 최적화된 응답 구성\n- 클라이언트 팀이 BFF를 직접 운영 가능\n- 클라이언트별 독립 배포\n- 불필요한 데이터 전송 제거 (모바일 최적화)\n\n**BFF 단점:**\n- 코드 중복 (여러 BFF에서 비슷한 로직)\n- 운영할 서비스 수 증가\n\n**실무 조합:**\n```\n[API Gateway] — 인증, Rate Limiting, SSL 종료\n    ↓\n[Web BFF]  /  [Mobile BFF]  /  [Partner BFF]\n    ↓                ↓                  ↓\n           [마이크로서비스들]\n```\n\n**GraphQL을 BFF로:**\n```\n[Web BFF = GraphQL]\n→ 클라이언트가 필요한 필드만 요청\n→ 여러 서비스 데이터를 단일 쿼리로 조합\n→ 오버패칭/언더패칭 해결\n```\n\n**선택 기준:**\n- 클라이언트 1~2개, 요구사항 유사 → API Gateway로 충분\n- 다양한 클라이언트, 요구사항 상이 → BFF\n- 팀이 클라이언트별로 분리 → BFF (Conway''s Law)',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', 'gRPC와 Protocol Buffers를 사용한 서비스 간 통신 설계 시 고려사항은?', '지알피씨와 프로토콜 버퍼스를 사용한 서비스 간 통신 설계 시 고려사항은?', 'API설계',
 '**gRPC 특성:**\n```\nHTTP/2 기반 + Protocol Buffers 직렬화\n→ REST보다 3~10배 빠른 성능\n→ 양방향 스트리밍 지원\n→ 강타입 계약 (코드 생성)\n```\n\n**Protocol Buffers 스키마:**\n```protobuf\n// order.proto\nsyntax = "proto3";\npackage order;\n\nservice OrderService {\n  rpc GetOrder (GetOrderRequest) returns (Order);\n  rpc CreateOrder (CreateOrderRequest) returns (Order);\n  rpc StreamOrders (StreamRequest) returns (stream Order); // 서버 스트리밍\n  rpc BatchCreateOrders (stream CreateOrderRequest) returns (BatchResult); // 클라이언트 스트리밍\n}\n\nmessage Order {\n  int64 id = 1;\n  int64 user_id = 2;\n  OrderStatus status = 3;\n  double amount = 4;\n  google.protobuf.Timestamp created_at = 5;\n}\n\nenum OrderStatus {\n  PENDING = 0;\n  CONFIRMED = 1;\n  SHIPPED = 2;\n}\n```\n\n**Java 서버 구현:**\n```java\n@GrpcService\npublic class OrderGrpcService extends OrderServiceGrpc.OrderServiceImplBase {\n    @Override\n    public void getOrder(GetOrderRequest req, StreamObserver<Order> observer) {\n        try {\n            Order order = orderService.findById(req.getId());\n            observer.onNext(order);\n            observer.onCompleted();\n        } catch (Exception e) {\n            observer.onError(Status.NOT_FOUND\n                .withDescription("Order not found: " + req.getId())\n                .asException());\n        }\n    }\n}\n```\n\n**스키마 진화 규칙:**\n```\n안전한 변경:\n+ 새 필드 추가 (새 필드 번호)\n+ 선택적 필드를 반복 필드로\n\n위험한 변경:\n- 필드 번호 변경 (역직렬화 오류)\n- 필드 타입 변경\n- 필드 번호 재사용 (삭제된 번호)\n\n안전한 삭제:\n1. 필드 사용 중단 (deprecated)\n2. reserved로 번호 예약\nreserved 3, 4;  // 삭제된 필드 번호 예약\nreserved "old_field_name";\n```\n\n**gRPC vs REST 선택:**\n| 상황 | gRPC | REST |\n|------|------|------|\n| 내부 서비스 통신 | ✅ | |\n| 외부 공개 API | | ✅ |\n| 실시간 스트리밍 | ✅ | |\n| 브라우저 클라이언트 | △ (gRPC-Web) | ✅ |\n| 대역폭 제한 환경 | ✅ | |',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', 'API 관리(API Management)와 개발자 포털(Developer Portal)을 어떻게 설계하나요?', '에이피아이 관리(에이피아이 Management)와 개발자 포털(Developer Portal)을 어떻게 설계하나요?', 'API설계',
 '**API 관리의 필요성:**\n외부 파트너/개발자에게 API를 제공할 때 보안, 사용량 제어, 문서화, 모니터링을 체계적으로 관리.\n\n**API 관리 핵심 기능:**\n\n**1. API Key 발급 및 관리:**\n```\n파트너 등록 → API Key 발급 (UUID v4)\n→ Key별 Rate Limit 설정\n→ Key별 허용 API 범위 설정 (Scope)\n→ Key 만료/재발급/폐기\n```\n\n**2. 사용량 제어 (Quota & Throttling):**\n```\n기본 티어: 1,000 req/day\n스탠다드 티어: 100,000 req/day\n엔터프라이즈 티어: 무제한\n\n초과 시: 429 Too Many Requests\nRetry-After: {reset_timestamp}\n```\n\n**3. API 버전 수명주기:**\n```\nAlpha → Beta → GA (General Availability) → Deprecated → Sunset\n\nDeprecation 정책:\n- 최소 6개월 전 공지\n- Sunset 헤더로 만료일 명시\n- 마이그레이션 가이드 제공\n```\n\n**4. 개발자 포털 구성:**\n```\n[개발자 포털 필수 요소]\n├── API 레퍼런스 (OpenAPI/Swagger 자동 생성)\n├── 시작하기 가이드 (Quickstart)\n├── 코드 샘플 (Java, Python, JS, Go)\n├── 대화형 API 탐색기 (Try It)\n├── SDK 다운로드\n├── 변경 로그 (Changelog)\n├── 상태 페이지 (Status Page)\n└── 커뮤니티 포럼\n```\n\n**5. OpenAPI 스펙 자동 생성 (Spring):**\n```java\n@Operation(summary = "주문 조회", description = "주문 ID로 상세 정보 조회")\n@ApiResponses({\n    @ApiResponse(responseCode = "200", description = "성공"),\n    @ApiResponse(responseCode = "404", description = "주문 없음")\n})\n@GetMapping("/orders/{id}")\npublic OrderResponse getOrder(@PathVariable Long id) { ... }\n```\n\n**6. 모니터링 대시보드 (파트너 제공):**\n```\n파트너별 사용량, 에러율, 레이턴시 리포트\n월별 청구서 연동\n```\n\n**솔루션:** AWS API Gateway + Developer Portal, Kong Enterprise, Azure API Management',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', 'API 설계에서 도메인 주도 설계(DDD)를 어떻게 반영하나요?', '에이피아이 설계에서 도메인 주도 설계(디디디)를 어떻게 반영하나요?', 'API설계',
 '**DDD와 API 설계의 연결:**\nDDD의 Bounded Context, Aggregate, 유비쿼터스 언어를 API 설계에 직접 반영.\n\n**Bounded Context → API 경계:**\n```\n[주문 컨텍스트]   → /api/orders/...\n[결제 컨텍스트]   → /api/payments/...\n[배송 컨텍스트]   → /api/shipments/...\n[카탈로그 컨텍스트] → /api/catalog/...\n\n각 컨텍스트는 독립 서비스 = 독립 API\n```\n\n**Aggregate를 API 자원으로:**\n```\n주문 Aggregate Root: Order (OrderItem, Payment를 포함)\n\nAPI 설계:\nPOST /orders                    — 주문 생성 (Aggregate 전체)\nGET  /orders/{id}               — 주문 조회 (Aggregate 전체)\nPOST /orders/{id}/confirm       — 주문 확정 (도메인 이벤트)\nPOST /orders/{id}/cancel        — 주문 취소 (도메인 이벤트)\n\n// NOT: /orders/{id}/items/{itemId} — Aggregate 내부 직접 접근 지양\n```\n\n**유비쿼터스 언어 → API 명명:**\n```\n비즈니스 용어를 그대로 API에 반영\n\n나쁜 예:\nPOST /orders/{id}/status (status=CONFIRMED)\n\n좋은 예:\nPOST /orders/{id}/confirm\nPOST /orders/{id}/cancel\nPOST /orders/{id}/ship\n→ 도메인 전문가와 개발자가 같은 언어 사용\n```\n\n**도메인 이벤트 기반 API:**\n```\n명령(Command): POST /orders/{id}/place\n→ 내부에서 OrderPlaced 이벤트 발행\n→ 외부 시스템은 이벤트 구독\n\n이벤트 웹훅 등록:\nPOST /webhooks\n{ event: "order.placed", url: "https://..." }\n```\n\n**컨텍스트 맵 → API 통합 패턴:**\n```\nShared Kernel: 두 컨텍스트가 공유 모델 사용\nCustomer/Supplier: 상류(주문)가 하류(배송) 요구사항에 맞춤\nAnticorruption Layer: 레거시 시스템과 경계에서 변환\n```\n\n**DTO와 도메인 객체 분리:**\n```java\n// API DTO — 외부 계약\npublic record OrderResponse(\n    Long id, String status, BigDecimal amount\n) {}\n\n// 도메인 객체 — 내부 로직\npublic class Order {\n    private OrderStatus status; // 내부 열거형\n    private Money amount;       // 값 객체\n    public void confirm() { ... }  // 도메인 로직\n}\n// 변환은 Application Service에서 담당\n```',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', '대규모 서비스에서 API 성능 최적화를 위한 전략을 종합적으로 설명해주세요.', '대규모 서비스에서 에이피아이 성능 최적화를 위한 전략을 종합적으로 설명해주세요.', 'API설계',
 '**API 성능 병목 분류:**\n```\n1. 네트워크 레이턴시\n2. 직렬화/역직렬화 비용\n3. DB 쿼리 성능\n4. 서비스 간 호출 레이턴시\n5. 애플리케이션 로직 처리 시간\n```\n\n**1. 연결 최적화:**\n```\nHTTP/2: 다중화(Multiplexing) — 동일 연결로 여러 요청 병렬\nHTTP/3 (QUIC): UDP 기반, 헤드오브라인 블로킹 제거\nKeep-Alive: 연결 재사용\nConnectionPool: DB, Redis 연결 풀 적절히 설정\n```\n\n**2. 응답 크기 최적화:**\n```\n압축: gzip/Brotli (60~80% 크기 감소)\nContent-Encoding: gzip\n\nField Filtering:\nGET /users/1?fields=id,name,email\n→ 필요한 필드만 반환\n\nSparse Fieldsets (JSON:API):\nGET /articles?fields[articles]=title,body\n```\n\n**3. 동시성 최적화:**\n```java\n// 독립적인 서비스 호출을 병렬로\nCompletableFuture<User> userFuture =\n    CompletableFuture.supplyAsync(() -> userService.get(userId));\nCompletableFuture<List<Order>> ordersFuture =\n    CompletableFuture.supplyAsync(() -> orderService.getByUser(userId));\n\nCompletableFuture.allOf(userFuture, ordersFuture).join();\nUser user = userFuture.get();\nList<Order> orders = ordersFuture.get();\n// 순차 호출 200ms+150ms=350ms → 병렬 200ms\n```\n\n**4. 캐싱 레이어:**\n```\nHTTP 캐싱:\nCache-Control: public, max-age=60\nETag: "abc123"\nIf-None-Match: "abc123" → 304 Not Modified (바디 전송 없음)\n\nConditional Request:\nIf-Modified-Since: 변경 없으면 304 → 대역폭 절약\n```\n\n**5. 페이지네이션 + 부분 응답:**\n```\nCursor 기반 페이지네이션 (Keyset)\nGET /orders?after=1234&limit=20\n→ WHERE id > 1234 LIMIT 20 (OFFSET보다 빠름)\n```\n\n**6. N+1 방지:**\n```java\n// 나쁜 예: N+1\norders.forEach(o -> o.setUser(userService.get(o.getUserId())));\n\n// 좋은 예: 배치 조회\nSet<Long> userIds = orders.stream()\n    .map(Order::getUserId).collect(toSet());\nMap<Long, User> users = userService.findAllById(userIds);\norders.forEach(o -> o.setUser(users.get(o.getUserId())));\n```\n\n**성능 측정 기준:**\n- P50, P95, P99 레이턴시\n- Apdex Score (응답 시간 만족도 지수)\n- 서비스별 SLO 대비 현재 지표',
 'MODEL_ANSWER', TRUE, NOW());

INSERT IGNORE INTO question_pool (cache_key, content, tts_content, category, model_answer, reference_type, is_active, created_at) VALUES
('SENIOR:SYSTEM_DESIGN', 'API 보안 설계에서 OWASP API Security Top 10을 기반으로 방어 전략을 설명해주세요.', '에이피아이 보안 설계에서 오와에스피 에이피아이 Security Top 10을 기반으로 방어 전략을 설명해주세요.', 'API설계',
 '**OWASP API Security Top 10 (2023) 주요 항목과 방어:**\n\n**1. Broken Object Level Authorization (BOLA/IDOR)**\n```\n공격: GET /orders/1234 → 다른 사용자 주문 조회\n\n방어:\n// 반드시 소유자 검증\npublic Order getOrder(Long orderId, Long requestingUserId) {\n    Order order = orderRepository.findById(orderId);\n    if (!order.getUserId().equals(requestingUserId)) {\n        throw new ForbiddenException();\n    }\n    return order;\n}\n// URL에 리소스 ID를 노출하기보다 JWT에서 userId 추출\n```\n\n**2. Broken Authentication**\n```\n방어:\n- JWT 서명 검증 필수 (alg:none 공격 방지)\n- 토큰 만료 검증\n- Refresh Token Rotation\n- 브루트포스 방어 (Rate Limiting + 계정 잠금)\n```\n\n**3. Broken Object Property Level Authorization**\n```\n공격: PATCH /users/1 { "role": "ADMIN" } — 권한 상승\n\n방어:\n@JsonIgnore private String role;  // 직접 바인딩 금지\n// DTO로 허용 필드만 명시적 수용\n```\n\n**4. Unrestricted Resource Consumption**\n```\n방어:\n- Rate Limiting (IP별, API Key별)\n- 요청 크기 제한 (max-body-size: 10MB)\n- 응답 타임아웃 설정\n- 페이지네이션으로 대용량 응답 제한\n```\n\n**5. Broken Function Level Authorization**\n```\n공격: 일반 사용자가 /admin/users 접근\n\n방어:\n@PreAuthorize("hasRole(''ADMIN'')")\n@GetMapping("/admin/users")\n// 모든 관리자 엔드포인트 명시적 인가\n```\n\n**6. Mass Assignment**\n```\n공격: POST /users { "name": "홍", "isAdmin": true }\n\n방어:\n// Request DTO에 허용 필드만\npublic record CreateUserRequest(\n    @NotBlank String name,\n    @Email String email\n    // isAdmin, role 등 민감 필드 제외\n) {}\n```\n\n**7. Security Misconfiguration**\n```\n방어:\n- CORS 화이트리스트 설정\n- 불필요한 HTTP 메서드 비활성화\n- 에러 응답에 스택 트레이스 제거\n- HTTPS Only\n```\n\n**8. SQL/NoSQL Injection**\n```java\n// JPA 파라미터 바인딩 (안전)\n@Query("SELECT u FROM User u WHERE u.email = :email")\nUser findByEmail(@Param("email") String email);\n// 절대 문자열 연결 금지\n```\n\n**9. Improper Assets Management**\n```\n방어:\n- API 인벤토리 관리 (모든 엔드포인트 문서화)\n- 구버전 API Sunset 정책 준수\n- Shadow API (문서화 안 된 API) 탐지\n```\n\n**10. Insufficient Logging & Monitoring**\n```java\n// 모든 인증 실패, 권한 오류, 이상 요청 로깅\nlog.warn("인가 실패: userId={}, resource={}, action={}", \n         userId, resource, action);\n// SIEM 연동으로 이상 패턴 실시간 탐지\n```',
 'MODEL_ANSWER', TRUE, NOW());
