spring:
  application:
    name: rehearse-api
  profiles:
    active: local

  threads:
    virtual:
      enabled: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

server:
  port: 8080
  tomcat:
    max-connections: 8192
    accept-count: 100

resilience4j:
  ratelimiter:
    instances:
      claude-api:
        limitForPeriod: 50
        limitRefreshPeriod: 1s
        timeoutDuration: 120s
      whisper-api:
        limitForPeriod: 50
        limitRefreshPeriod: 1s
        timeoutDuration: 120s

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
